/** Generated by scripts/generate-additive-schemas.mjs. Do not edit. */
import { z } from 'zod';

export const OpaqueId = z.string().refine(value => Array.from(value).length >= 1).regex(new RegExp("^[A-Za-z0-9][A-Za-z0-9._-]*$"));
export type OpaqueId = z.infer<typeof OpaqueId>;

export const ControlRevision = z.string().regex(new RegExp("^(0|[1-9][0-9]*)$"));
export type ControlRevision = z.infer<typeof ControlRevision>;

export const Timestamp = z.iso.datetime({ offset: false }).refine(value => /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?Z$/.test(value)).regex(new RegExp("Z$"));
export type Timestamp = z.infer<typeof Timestamp>;

export const MapRevision = z.union([z.string().regex(new RegExp("^([0-9a-f]{16}:[1-9][0-9]*|none:0)$")), z.null()]);
export type MapRevision = z.infer<typeof MapRevision>;

export const Reason = z.strictObject({
  "code": z.string(),
  "message": z.union([z.string(), z.null()]),
});
export type Reason = z.infer<typeof Reason>;

export const Sha256 = z.string().regex(new RegExp("^[0-9a-f]{64}$"));
export type Sha256 = z.infer<typeof Sha256>;

export const ObjectId = z.string().regex(new RegExp("^([0-9a-f]{40}|[0-9a-f]{64})$"));
export type ObjectId = z.infer<typeof ObjectId>;

export const MapVocab = z.string().refine(value => Array.from(value).length >= 1).refine(value => Array.from(value).length <= 32);
export type MapVocab = z.infer<typeof MapVocab>;

export const BoundedCount = z.number().int().min(0).max(9007199254740991);
export type BoundedCount = z.infer<typeof BoundedCount>;

export const MapGenerator = z.strictObject({
  "name": MapVocab,
  "version": BoundedCount,
  "ruleset_sha256": Sha256,
});
export type MapGenerator = z.infer<typeof MapGenerator>;

export const MapSummary = z.strictObject({
  "root": Sha256,
  "status": z.string(),
  "reasons": z.array(Reason).max(250),
  "selected": z.boolean(),
  "source_revision": z.union([ObjectId, z.null()]),
  "source_tree": z.union([ObjectId, z.null()]),
  "object_format": z.union([z.string(), z.null()]),
  "generator": z.union([MapGenerator, z.null()]),
});
export type MapSummary = z.infer<typeof MapSummary>;

export const MapText = z.string().refine(value => Array.from(value).length <= 520);
export type MapText = z.infer<typeof MapText>;

export const MapFreshness = z.strictObject({
  "status": z.string(),
  "reasons": z.array(Reason).max(250),
  "against_commit": z.union([ObjectId, z.null()]),
  "against_tree": z.union([ObjectId, z.null()]),
  "metadata_paths": z.array(MapText).max(50),
  "metadata_paths_omitted": BoundedCount,
});
export type MapFreshness = z.infer<typeof MapFreshness>;

export const EntityRef = z.strictObject({
  "id": OpaqueId,
  "kind": z.string(),
  "title": z.union([z.string(), z.null()]),
});
export type EntityRef = z.infer<typeof EntityRef>;

export const ArchitectureFreshness = z.strictObject({
  "status": z.string(),
  "reasons": z.array(Reason).max(250),
  "basis": z.union([MapVocab, z.null()]),
  "observed_commit": z.union([ObjectId, z.null()]),
  "authoritative_commit": z.union([ObjectId, z.null()]),
  "scope": z.union([MapVocab, z.null()]),
  "changed_paths": z.array(MapText).max(50),
  "changed_paths_omitted": BoundedCount,
});
export type ArchitectureFreshness = z.infer<typeof ArchitectureFreshness>;

export const ReferenceLabel = z.string().refine(value => Array.from(value).length >= 1);
export type ReferenceLabel = z.infer<typeof ReferenceLabel>;

export const ArchitectureReference = z.strictObject({
  "evidence": z.union([EntityRef, z.null()]),
  "freshness": ArchitectureFreshness,
  "note": ReferenceLabel,
});
export type ArchitectureReference = z.infer<typeof ArchitectureReference>;

export const MapsOverview = z.strictObject({
  "map_revision": MapRevision,
  "registry": z.strictObject({
  "state": z.string(),
  "reasons": z.array(Reason).max(250),
}),
  "structural": z.strictObject({
  "state": z.string(),
  "reasons": z.array(Reason).max(250),
  "summary": z.union([MapSummary, z.null()]),
  "freshness": z.union([MapFreshness, z.null()]),
}),
  "architecture": z.union([ArchitectureReference, z.null()]),
  "stored": z.strictObject({
  "count": BoundedCount,
}),
  "label": ReferenceLabel,
});
export type MapsOverview = z.infer<typeof MapsOverview>;

export const MapsResponse = z.strictObject({
  "schema_version": z.literal("0.1.3"),
  "project_id": OpaqueId,
  "control_revision": ControlRevision,
  "generated_at": Timestamp,
  "data": MapsOverview,
});
export type MapsResponse = z.infer<typeof MapsResponse>;

export const Cursor = z.string().refine(value => Array.from(value).length >= 1);
export type Cursor = z.infer<typeof Cursor>;

export const StructuralListResponse = z.strictObject({
  "schema_version": z.literal("0.1.3"),
  "project_id": OpaqueId,
  "control_revision": ControlRevision,
  "generated_at": Timestamp,
  "data": z.strictObject({
  "items": z.array(MapSummary).max(50),
  "next_cursor": z.union([Cursor, z.null()]),
  "scan_incomplete": z.union([z.strictObject({
  "examined": BoundedCount,
  "stored": BoundedCount,
  "reasons": z.array(Reason).max(250),
}), z.null()]),
  "label": ReferenceLabel,
}),
});
export type StructuralListResponse = z.infer<typeof StructuralListResponse>;

export const MapLimits = z.strictObject({
  "tracked_paths": z.strictObject({
  "seen": BoundedCount.optional(),
  "capped": z.boolean().optional(),
}).optional(),
  "metadata_bytes": z.strictObject({
  "read": BoundedCount.optional(),
  "limit": BoundedCount.optional(),
  "capped": z.boolean().optional(),
}).optional(),
  "metadata_blob_bytes": z.strictObject({
  "limit": BoundedCount.optional(),
  "skipped": BoundedCount.optional(),
}).optional(),
});
export type MapLimits = z.infer<typeof MapLimits>;

export const MapInputsSummary = z.strictObject({
  "path_listing_sha256": Sha256,
  "count": BoundedCount,
  "read": BoundedCount,
  "capped_size": BoundedCount,
  "capped_total": BoundedCount,
});
export type MapInputsSummary = z.infer<typeof MapInputsSummary>;

export const MapDirectoryRow = z.strictObject({
  "path": MapText,
  "depth": BoundedCount.optional(),
  "files": BoundedCount.optional(),
  "languages": z.array(MapVocab).max(20),
  "languages_omitted": BoundedCount,
  "label": MapVocab,
});
export type MapDirectoryRow = z.infer<typeof MapDirectoryRow>;

export const MapSubmodule = z.strictObject({
  "path": MapText,
  "object": ObjectId.optional(),
});
export type MapSubmodule = z.infer<typeof MapSubmodule>;

export const MapDirectoriesSection = z.strictObject({
  "max_depth": BoundedCount.optional(),
  "rows": z.array(MapDirectoryRow).max(200),
  "rows_total": BoundedCount.optional(),
  "rows_omitted": BoundedCount.optional(),
  "submodules": z.array(MapSubmodule).max(200),
  "submodules_omitted": BoundedCount.optional(),
  "dropped_fields": BoundedCount,
  "dropped_items": BoundedCount,
});
export type MapDirectoriesSection = z.infer<typeof MapDirectoriesSection>;

export const MapUnknownExtension = z.strictObject({
  "extension": MapText,
  "files": BoundedCount.optional(),
});
export type MapUnknownExtension = z.infer<typeof MapUnknownExtension>;

export const MapLanguagesSection = z.strictObject({
  "counts": z.record(z.string().refine(value => Array.from(value).length >= 1).refine(value => Array.from(value).length <= 32), BoundedCount).refine(value => Object.keys(value).length <= 100),
  "counts_omitted": BoundedCount,
  "unknown_files": BoundedCount.optional(),
  "unknown_extensions": z.array(MapUnknownExtension).max(20),
  "unknown_extensions_omitted": BoundedCount.optional(),
  "dropped_fields": BoundedCount,
  "dropped_items": BoundedCount,
});
export type MapLanguagesSection = z.infer<typeof MapLanguagesSection>;

export const MapBuildDescriptor = z.strictObject({
  "path": MapText,
  "kind": MapVocab,
  "status": MapVocab,
});
export type MapBuildDescriptor = z.infer<typeof MapBuildDescriptor>;

export const MapBuildDescriptorsSection = z.strictObject({
  "items": z.array(MapBuildDescriptor).max(200),
  "omitted": BoundedCount.optional(),
  "dropped_fields": BoundedCount,
  "dropped_items": BoundedCount,
});
export type MapBuildDescriptorsSection = z.infer<typeof MapBuildDescriptorsSection>;

export const MapEntryPoint = z.strictObject({
  "label": MapVocab,
  "path": MapText,
  "name": MapText.optional(),
  "target": MapText.optional(),
  "rule": MapVocab.optional(),
});
export type MapEntryPoint = z.infer<typeof MapEntryPoint>;

export const MapEntryPointsSection = z.strictObject({
  "items": z.array(MapEntryPoint).max(100),
  "omitted": BoundedCount.optional(),
  "dropped_fields": BoundedCount,
  "dropped_items": BoundedCount,
});
export type MapEntryPointsSection = z.infer<typeof MapEntryPointsSection>;

export const MapTestCandidate = z.strictObject({
  "kind": MapVocab,
  "path": MapText.optional(),
  "pattern": MapText.optional(),
  "files": BoundedCount.optional(),
  "runner": MapVocab.optional(),
  "source": MapVocab.optional(),
});
export type MapTestCandidate = z.infer<typeof MapTestCandidate>;

export const MapTestCandidatesSection = z.strictObject({
  "items": z.array(MapTestCandidate).max(100),
  "omitted": BoundedCount.optional(),
  "dropped_fields": BoundedCount,
  "dropped_items": BoundedCount,
});
export type MapTestCandidatesSection = z.infer<typeof MapTestCandidatesSection>;

export const MapGeneratedOrVendor = z.strictObject({
  "kind": MapVocab,
  "source": MapVocab,
  "pattern": MapText,
  "files": BoundedCount.optional(),
  "attributes_file": MapText.optional(),
});
export type MapGeneratedOrVendor = z.infer<typeof MapGeneratedOrVendor>;

export const MapGeneratedAndVendorSection = z.strictObject({
  "items": z.array(MapGeneratedOrVendor).max(200),
  "omitted": BoundedCount.optional(),
  "dropped_fields": BoundedCount,
  "dropped_items": BoundedCount,
});
export type MapGeneratedAndVendorSection = z.infer<typeof MapGeneratedAndVendorSection>;

export const MapSemanticPrerequisite = z.strictObject({
  "path": MapText,
  "kind": MapVocab,
  "source": MapVocab,
});
export type MapSemanticPrerequisite = z.infer<typeof MapSemanticPrerequisite>;

export const MapSemanticPrerequisitesSection = z.strictObject({
  "items": z.array(MapSemanticPrerequisite).max(100),
  "omitted": BoundedCount.optional(),
  "dropped_fields": BoundedCount,
  "dropped_items": BoundedCount,
});
export type MapSemanticPrerequisitesSection = z.infer<typeof MapSemanticPrerequisitesSection>;

export const MapCapHit = z.strictObject({
  "section": MapVocab,
  "field": MapVocab,
  "limit": BoundedCount.optional(),
  "omitted": BoundedCount.optional(),
});
export type MapCapHit = z.infer<typeof MapCapHit>;

export const MapParseFailure = z.strictObject({
  "path": MapText,
  "code": MapVocab,
});
export type MapParseFailure = z.infer<typeof MapParseFailure>;

export const MapUnsupported = z.strictObject({
  "path": MapText,
  "reason": MapVocab,
});
export type MapUnsupported = z.infer<typeof MapUnsupported>;

export const MapLimitsAndOmissionsSection = z.strictObject({
  "caps_hit": z.array(MapCapHit).max(20),
  "caps_hit_omitted": BoundedCount.optional(),
  "parse_failures": z.array(MapParseFailure).max(100),
  "parse_failures_omitted": BoundedCount.optional(),
  "unsupported": z.array(MapUnsupported).max(100),
  "unsupported_omitted": BoundedCount.optional(),
  "lfs_pointers": z.array(MapText).max(100),
  "lfs_pointers_omitted": BoundedCount.optional(),
  "metadata_unread": BoundedCount.optional(),
  "non_utf8_names": BoundedCount.optional(),
  "symlinks": BoundedCount.optional(),
  "submodules": BoundedCount.optional(),
  "unknown_extension_files": BoundedCount.optional(),
  "dropped_fields": BoundedCount,
  "dropped_items": BoundedCount,
});
export type MapLimitsAndOmissionsSection = z.infer<typeof MapLimitsAndOmissionsSection>;

export const MapSections = z.strictObject({
  "directories": MapDirectoriesSection.optional(),
  "languages": MapLanguagesSection.optional(),
  "build_descriptors": MapBuildDescriptorsSection.optional(),
  "entry_point_candidates": MapEntryPointsSection.optional(),
  "test_candidates": MapTestCandidatesSection.optional(),
  "generated_and_vendor": MapGeneratedAndVendorSection.optional(),
  "semantic_prerequisites": MapSemanticPrerequisitesSection.optional(),
  "limits_and_omissions": MapLimitsAndOmissionsSection.optional(),
});
export type MapSections = z.infer<typeof MapSections>;

export const StructuralDetailResponse = z.strictObject({
  "schema_version": z.literal("0.1.3"),
  "project_id": OpaqueId,
  "control_revision": ControlRevision,
  "generated_at": Timestamp,
  "data": z.strictObject({
  "summary": MapSummary,
  "freshness": MapFreshness,
  "limits": MapLimits,
  "inputs": MapInputsSummary,
  "sections": MapSections,
  "cut_strings": BoundedCount,
  "dropped_fields": BoundedCount,
  "label": ReferenceLabel,
}),
});
export type StructuralDetailResponse = z.infer<typeof StructuralDetailResponse>;

export const MapInput = z.strictObject({
  "path": MapText,
  "git_oid": ObjectId.optional(),
  "size": BoundedCount.optional(),
  "read": z.boolean(),
  "sha256": Sha256.optional(),
  "reason": z.string().optional(),
});
export type MapInput = z.infer<typeof MapInput>;

export const StructuralInputsResponse = z.strictObject({
  "schema_version": z.literal("0.1.3"),
  "project_id": OpaqueId,
  "control_revision": ControlRevision,
  "generated_at": Timestamp,
  "data": z.strictObject({
  "root": Sha256,
  "items": z.array(MapInput).max(250),
  "next_cursor": z.union([Cursor, z.null()]),
  "cut_strings": BoundedCount,
  "dropped_fields": BoundedCount,
  "label": ReferenceLabel,
}),
});
export type StructuralInputsResponse = z.infer<typeof StructuralInputsResponse>;

export const MapDiffOperand = z.strictObject({
  "root": Sha256,
  "source_revision": ObjectId,
  "source_tree": ObjectId,
});
export type MapDiffOperand = z.infer<typeof MapDiffOperand>;

export const MapEnvelopeChanges = z.strictObject({
  "source_revision": z.strictObject({
  "from": ObjectId,
  "to": ObjectId,
}).optional(),
  "source_tree": z.strictObject({
  "from": ObjectId,
  "to": ObjectId,
}).optional(),
  "object_format": z.strictObject({
  "from": MapVocab,
  "to": MapVocab,
}).optional(),
  "generator": z.strictObject({
  "from": MapGenerator,
  "to": MapGenerator,
}).optional(),
  "path_listing_sha256": z.strictObject({
  "from": Sha256,
  "to": Sha256,
}).optional(),
});
export type MapEnvelopeChanges = z.infer<typeof MapEnvelopeChanges>;

export const MapValueChanges = z.record(z.string().refine(value => Array.from(value).length >= 1).refine(value => Array.from(value).length <= 64), z.strictObject({
  "from": z.union([BoundedCount, z.boolean(), z.null()]),
  "to": z.union([BoundedCount, z.boolean(), z.null()]),
})).refine(value => Object.keys(value).length <= 128);
export type MapValueChanges = z.infer<typeof MapValueChanges>;

export const MapDirectoriesChange = z.strictObject({
  "changed": z.boolean(),
  "beyond_cap": z.boolean(),
  "rows": z.strictObject({
  "added": z.array(MapDirectoryRow).max(200),
  "removed": z.array(MapDirectoryRow).max(200),
}).optional(),
  "submodules": z.strictObject({
  "added": z.array(MapSubmodule).max(200),
  "removed": z.array(MapSubmodule).max(200),
}).optional(),
  "values": MapValueChanges,
});
export type MapDirectoriesChange = z.infer<typeof MapDirectoriesChange>;

export const MapLanguagesChange = z.strictObject({
  "changed": z.boolean(),
  "beyond_cap": z.boolean(),
  "unknown_extensions": z.strictObject({
  "added": z.array(MapUnknownExtension).max(20),
  "removed": z.array(MapUnknownExtension).max(20),
}).optional(),
  "values": MapValueChanges,
});
export type MapLanguagesChange = z.infer<typeof MapLanguagesChange>;

export const MapBuildDescriptorsChange = z.strictObject({
  "changed": z.boolean(),
  "beyond_cap": z.boolean(),
  "items": z.strictObject({
  "added": z.array(MapBuildDescriptor).max(200),
  "removed": z.array(MapBuildDescriptor).max(200),
}).optional(),
  "values": MapValueChanges,
});
export type MapBuildDescriptorsChange = z.infer<typeof MapBuildDescriptorsChange>;

export const MapEntryPointsChange = z.strictObject({
  "changed": z.boolean(),
  "beyond_cap": z.boolean(),
  "items": z.strictObject({
  "added": z.array(MapEntryPoint).max(100),
  "removed": z.array(MapEntryPoint).max(100),
}).optional(),
  "values": MapValueChanges,
});
export type MapEntryPointsChange = z.infer<typeof MapEntryPointsChange>;

export const MapTestCandidatesChange = z.strictObject({
  "changed": z.boolean(),
  "beyond_cap": z.boolean(),
  "items": z.strictObject({
  "added": z.array(MapTestCandidate).max(100),
  "removed": z.array(MapTestCandidate).max(100),
}).optional(),
  "values": MapValueChanges,
});
export type MapTestCandidatesChange = z.infer<typeof MapTestCandidatesChange>;

export const MapGeneratedAndVendorChange = z.strictObject({
  "changed": z.boolean(),
  "beyond_cap": z.boolean(),
  "items": z.strictObject({
  "added": z.array(MapGeneratedOrVendor).max(200),
  "removed": z.array(MapGeneratedOrVendor).max(200),
}).optional(),
  "values": MapValueChanges,
});
export type MapGeneratedAndVendorChange = z.infer<typeof MapGeneratedAndVendorChange>;

export const MapSemanticPrerequisitesChange = z.strictObject({
  "changed": z.boolean(),
  "beyond_cap": z.boolean(),
  "items": z.strictObject({
  "added": z.array(MapSemanticPrerequisite).max(100),
  "removed": z.array(MapSemanticPrerequisite).max(100),
}).optional(),
  "values": MapValueChanges,
});
export type MapSemanticPrerequisitesChange = z.infer<typeof MapSemanticPrerequisitesChange>;

export const MapLimitsAndOmissionsChange = z.strictObject({
  "changed": z.boolean(),
  "beyond_cap": z.boolean(),
  "caps_hit": z.strictObject({
  "added": z.array(MapCapHit).max(20),
  "removed": z.array(MapCapHit).max(20),
}).optional(),
  "parse_failures": z.strictObject({
  "added": z.array(MapParseFailure).max(100),
  "removed": z.array(MapParseFailure).max(100),
}).optional(),
  "unsupported": z.strictObject({
  "added": z.array(MapUnsupported).max(100),
  "removed": z.array(MapUnsupported).max(100),
}).optional(),
  "lfs_pointers": z.strictObject({
  "added": z.array(MapText).max(100),
  "removed": z.array(MapText).max(100),
}).optional(),
  "values": MapValueChanges,
});
export type MapLimitsAndOmissionsChange = z.infer<typeof MapLimitsAndOmissionsChange>;

export const MapDiffResponse = z.strictObject({
  "schema_version": z.literal("0.1.3"),
  "project_id": OpaqueId,
  "control_revision": ControlRevision,
  "generated_at": Timestamp,
  "data": z.strictObject({
  "a": MapDiffOperand,
  "b": MapDiffOperand,
  "identical": z.boolean(),
  "envelope": MapEnvelopeChanges,
  "sections": z.strictObject({
  "directories": MapDirectoriesChange,
  "languages": MapLanguagesChange,
  "build_descriptors": MapBuildDescriptorsChange,
  "entry_point_candidates": MapEntryPointsChange,
  "test_candidates": MapTestCandidatesChange,
  "generated_and_vendor": MapGeneratedAndVendorChange,
  "semantic_prerequisites": MapSemanticPrerequisitesChange,
  "limits_and_omissions": MapLimitsAndOmissionsChange,
}),
  "cut_strings": BoundedCount,
  "dropped_fields": BoundedCount,
  "dropped_items": BoundedCount,
  "label": ReferenceLabel,
}),
});
export type MapDiffResponse = z.infer<typeof MapDiffResponse>;

export const HistorySearchHit = z.strictObject({
  "id": OpaqueId,
  "kind": z.string(),
  "at": Timestamp,
  "subject": z.union([OpaqueId, z.null()]),
  "source": z.string(),
  "trust": z.strictObject({
  "source": z.string(),
  "label": ReferenceLabel,
}),
  "truncated": z.boolean(),
  "snippet": z.string().refine(value => Array.from(value).length <= 400),
  "expand": z.strictObject({
  "cli": z.array(z.string().refine(value => Array.from(value).length >= 1).refine(value => Array.from(value).length <= 256)).min(1).max(8),
  "link": z.union([EntityRef, z.null()]),
}),
});
export type HistorySearchHit = z.infer<typeof HistorySearchHit>;

export const HistorySearch = z.strictObject({
  "label": ReferenceLabel,
  "trust_label": ReferenceLabel,
  "query": z.strictObject({
  "terms": z.array(z.string().refine(value => Array.from(value).length >= 1).refine(value => Array.from(value).length <= 512)).min(1).max(16),
  "kinds": z.array(z.string()).max(16),
  "since": z.union([Timestamp, z.null()]),
  "until": z.union([Timestamp, z.null()]),
  "limit": z.number().int().min(1).max(50),
}),
  "fence": z.strictObject({
  "open": z.string().refine(value => Array.from(value).length >= 1).refine(value => Array.from(value).length <= 64),
  "close": z.string().refine(value => Array.from(value).length >= 1).refine(value => Array.from(value).length <= 64),
}),
  "hits": z.array(HistorySearchHit).max(50),
  "coverage": z.strictObject({
  "complete": z.boolean(),
  "indexed_through": z.union([BoundedCount, z.null()]),
  "history_entries": BoundedCount,
  "reasons": z.array(Reason).max(250),
}),
  "unverified": z.union([z.strictObject({
  "count": z.number().int().min(1).max(9007199254740991),
}), z.null()]),
});
export type HistorySearch = z.infer<typeof HistorySearch>;

export const HistorySearchResponse = z.strictObject({
  "schema_version": z.literal("0.1.3"),
  "project_id": OpaqueId,
  "control_revision": ControlRevision,
  "generated_at": Timestamp,
  "data": HistorySearch,
});
export type HistorySearchResponse = z.infer<typeof HistorySearchResponse>;

export const additiveResponseSchemas = { MapsResponse, StructuralListResponse, StructuralDetailResponse, StructuralInputsResponse, MapDiffResponse, HistorySearchResponse };
