"""The narrow interfaces between the Engine's collaborators (register E5).

Each collaborator depends on the ``Kernel``, on the seams (``seams``), and on the collaborators it uses only through
the protocol here: the members other collaborators actually call, nothing more. Which collaborator implements each
protocol is decided by the composition root (``api.Engine``). ``tests/unit/test_engine_composition.py`` keeps them
narrow: every member a collaborator uses is declared, every declared member is used and public, and every
implementation provides each member with the same signature.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any, Protocol

if TYPE_CHECKING:
    from aew import roles
    from aew.engine.base import TxnContext
    from aew.engine.dispatch import DispatchDecision
    from aew.history.index import HistoryIndex
    from aew.knowledge import context as ctxmod


class WorkUnitsPort(Protocol):
    """What other collaborators use of ``WorkUnits``."""

    def ancestor_plan_snapshot(self, state: dict[str, Any], work_id: str) -> dict[str, Any]: ...
    def before_commit(self, ctx: TxnContext) -> None: ...
    def check_guard(self, name: str | None, ctx: TxnContext, work_id: str, unit: dict[str, Any], to: str) -> None: ...
    def check_parent(self, state: dict[str, Any], kind: str, parent: str) -> None: ...
    def completion_sha(self, state: dict[str, Any], work_id: str) -> str | None: ...
    def dispatch_binding_problem(self, state: dict[str, Any], work_id: str) -> dict[str, Any] | None: ...
    def parse_edges(self, state: dict[str, Any], specs: list[str]) -> list[dict[str, str]]: ...
    def plan_binding_problem(self, state: dict[str, Any], work_id: str) -> dict[str, Any] | None: ...
    def propose(self, ctx: TxnContext, work_id: str, unit: dict[str, Any], *, body: str, reason: str | None,
                affected_paths: list[str] | None, assurance: dict[str, list[str]],
                author: dict[str, Any] | None = None,
                source_evidence: dict[str, Any] | None = None) -> tuple[str, int]: ...
    @staticmethod
    def refuse_cycles(state: dict[str, Any]) -> None: ...
    def require_dispatch_binding(self, state: dict[str, Any], work_id: str) -> None: ...
    def require_plan_binding(self, state: dict[str, Any], work_id: str) -> None: ...
    @staticmethod
    def rollup(state: dict[str, Any], work_id: str) -> dict[str, Any]: ...
    def set_state(self, unit: dict[str, Any], to: str, reason: str | None, *,
                  state: dict[str, Any]) -> dict[str, str]: ...
    def unit(self, state: dict[str, Any], work_id: str) -> dict[str, Any]: ...
    def view(self, state: dict[str, Any], work_id: str) -> dict[str, Any]: ...


class RolesPort(Protocol):
    """What other collaborators use of ``Roles``."""

    def bind_plan_assurance(self, unit: dict[str, Any], revision: int,
                            assurance: dict[str, list[str]] | None) -> None: ...
    def effective_role_plan(self, state: dict[str, Any], work_id: str,
                            gc: dict[str, Any] | None = None) -> dict[str, Any]: ...
    @staticmethod
    def pin_on(ctx: TxnContext, inv_id: str, card: roles.Card) -> None: ...
    @staticmethod
    def plan_gates(unit: dict[str, Any]) -> dict[str, str]: ...
    def policy_problems(self) -> list[str]: ...
    def resolve_card(self, state: dict[str, Any], work_id: str, slot: str, *, card_id: str | None,
                     role: str | None, gc: dict[str, Any] | None = None) -> roles.Card: ...
    def resolve_plan_assurance(self, unit: dict[str, Any], *, review: list[str] | None, verify: list[str] | None,
                               none: bool) -> dict[str, list[str]]: ...
    def role_catalog(self) -> roles.Catalog: ...
    def slot_ok(self, unit: dict[str, Any], slot: str, card: roles.Card) -> None: ...


class InvocationsPort(Protocol):
    """What other collaborators use of ``Invocations``."""

    @staticmethod
    def card_ref(inv: dict[str, Any]) -> dict[str, Any] | None: ...
    def complete_invocation(self, state: dict[str, Any], inv_id: str, status: str = "completed") -> None: ...
    def current_snapshot(self, unit: dict[str, Any]) -> dict[str, Any] | None: ...
    @staticmethod
    def execution_provenance(inv: dict[str, Any]) -> dict[str, Any]: ...
    def inspect_workspace(self, unit: dict[str, Any]) -> dict[str, Any]: ...
    def invocation_workspace(self, state: dict[str, Any], inv: dict[str, Any]) -> tuple[Path, str, str | None]: ...
    def new_invocation(
        self,
        ctx: TxnContext,
        role: str,
        work_id: str,
        *,
        scope: str = "ticket",
        specialty: str | None = None,
        workspace: str | None = None,
        workspace_id: str | None = None,
        snapshot: dict[str, Any] | None = None,
        card: Any = None,
    ) -> tuple[str, str]: ...
    def release_workspace(self, ctx: TxnContext, unit: dict[str, Any], why: str) -> None: ...
    def require_launchable(self, state: dict[str, Any], inv_id: str, *, relaunch: bool = True) -> dict[str, Any]: ...
    def snapshot_of(self, path: str | Path, workspace_id: str) -> dict[str, Any]: ...


class InputsPort(Protocol):
    """What other collaborators use of ``Inputs``."""

    def acknowledged(self, unit: dict[str, Any], evidence_id: str, sha: str, commit: str) -> dict[str, Any] | None: ...
    def dispatch_inputs(self, state: dict[str, Any], work_id: str, commit: str | None) -> list[dict[str, Any]]: ...
    def find_unit_evidence(self, work_id: str, evidence_id: str) -> dict[str, Any]: ...
    def input_status(self, state: dict[str, Any], work_id: str) -> list[dict[str, Any]]: ...
    def same_source(self, observed: str | None, current: str | None) -> bool: ...


class ContextPacksPort(Protocol):
    """What other collaborators use of ``ContextPacks``."""

    def build_pack(self, ctx: TxnContext, inv_id: str) -> None: ...
    def pack_inputs(self, state: dict[str, Any], inv_id: str) -> tuple[ctxmod.PackInputs, list[dict[str, Any]]]: ...
    def pack_rel(self, inv_id: str) -> str: ...


class GatesPort(Protocol):
    """What other collaborators use of ``Gates``."""

    PRE_REVIEW: list[str]
    def accepted_gate_context(self, state: dict[str, Any], work_id: str) -> dict[str, Any]: ...
    def binding_problem(self, unit: dict[str, Any]) -> dict[str, Any] | None: ...
    def find_evidence(self, work_id: str, evidence_id: str) -> dict[str, Any]: ...
    def gate_context(self, state: dict[str, Any], work_id: str) -> dict[str, Any]: ...
    def ingest_ref(self, unit: dict[str, Any], ev: dict[str, Any]) -> None: ...
    @staticmethod
    def integration_binding(unit: dict[str, Any]) -> dict[str, Any]: ...
    def plan_gate_status(self, state: dict[str, Any], work_id: str) -> dict[str, Any]: ...
    def record_meta(self, unit: dict[str, Any]) -> dict[str, Any]: ...
    def record_relied_on(self, ctx: TxnContext, unit: dict[str, Any], gc: dict[str, Any], names: list[str]) -> None: ...
    def require_bound_report(self, state: dict[str, Any], unit: dict[str, Any], ev: dict[str, Any], *,
                             scope: str) -> None: ...
    def require_current_binding(self, unit: dict[str, Any]) -> None: ...
    def require_gates(self, gc: dict[str, Any], names: list[str], *, what: str) -> None: ...
    def require_reported_workspace(self, work_id: str, unit: dict[str, Any], gc: dict[str, Any]) -> None: ...
    def require_workspace_intact(self, inv_id: str, inv: dict[str, Any], workspace: Path, ws_id: str) -> None: ...
    def review_gates(self, gc: dict[str, Any]) -> list[str]: ...
    def verification_gates(self, gc: dict[str, Any]) -> list[str]: ...


class WorkCommandsPort(Protocol):
    """What other collaborators use of ``WorkCommands``."""

    def work_reconcile(self, *, token: str, expect_rev: int, work_id: str, to: str, reason: str,
                       inspection: dict[str, Any] | None = None) -> dict[str, Any]: ...


class NonMutatingPort(Protocol):
    """What other collaborators use of ``NonMutating``."""

    def dispatch_observer(self, ctx: TxnContext, work_id: str, *, card: Any, scope: str, commit: str,
                          attempt: int | None = None, subject: dict[str, Any] | None = None,
                          inputs: list[dict[str, Any]] | None = None,
                          children_digest: str | None = None) -> tuple[str, str, dict[str, Any]]: ...
    def execute_record_binding(self, state: dict[str, Any], inv_id: str, inv: dict[str, Any], kind: str,
                               submitted: dict[str, Any]) -> dict[str, Any]: ...
    def prune_observations(self, state: dict[str, Any] | None = None) -> list[str]: ...
    @staticmethod
    def record_review_findings(unit: dict[str, Any], ev: dict[str, Any], evidence_id: str) -> None: ...
    def require_observation_intact(self, inv_id: str, inv: dict[str, Any]) -> None: ...


class HierarchyPort(Protocol):
    """What other collaborators use of ``Hierarchy``."""

    def children_digest(self, state: dict[str, Any], work_id: str) -> str: ...
    def work_tree(self, root: str | None = None) -> dict[str, Any]: ...


class LeadPort(Protocol):
    """What other collaborators use of ``Lead``."""

    def write_handoff(self, ctx: TxnContext, note: str, carry: list[str]) -> str: ...


class StatusViewsPort(Protocol):
    """What other collaborators use of ``StatusViews``."""

    def contradictions(self, state: dict[str, Any]) -> list[str]: ...


class HarnessPort(Protocol):
    """What other collaborators use of ``Harness``."""

    def after_implementation(self, state: dict[str, Any], wid: str) -> str: ...
    def harness_resume(self, state: dict[str, Any]) -> list[dict[str, Any]]: ...
    def implementation_blocker(self, state: dict[str, Any], wid: str) -> str | None: ...


class ArchivePort(Protocol):
    """What other collaborators use of ``Archive``."""

    def annotate(self, ctx: TxnContext, subject: str, rel: str, obj: str | None, *, decision: str | None = None,
                 note: str | None = None, cited: list[dict[str, Any]] | None = None) -> str: ...
    def archived_child_ids(self, state: dict[str, Any], parent: str) -> list[str]: ...
    def archived_children(self, state: dict[str, Any], parent: str) -> list[tuple[str, dict[str, Any]]]: ...
    def archived_credential(self, state: dict[str, Any], token_id: str) -> dict[str, Any] | None: ...
    def archived_invocation(self, state: dict[str, Any], inv_id: str) -> dict[str, Any] | None: ...
    def archived_tickets_below(self, state: dict[str, Any], parent: str, finished: str) -> list[str]: ...
    def archived_unit(self, state: dict[str, Any], work_id: str) -> dict[str, Any] | None: ...
    def archived_units(self, state: dict[str, Any], finished: str) -> list[dict[str, Any]]: ...
    def close_legacy(self, ctx: TxnContext, work_ids: list[str]) -> list[dict[str, Any]]: ...
    def end_lead_credentials(self, session: Any) -> dict[str, Any] | None: ...
    def facts_from_cold(self, state: dict[str, Any], work_id: str) -> dict[str, Any] | None: ...
    def index(self, state: dict[str, Any]) -> HistoryIndex: ...
    def legacy_units(self, state: dict[str, Any]) -> list[str]: ...
    def move(self, ctx: TxnContext, work_id: str, unit: dict[str, Any], new_parent: str | None, *,
             decision: str | None, note: str) -> str: ...
    def move_hot_subtree(self, state: dict[str, Any], unit: dict[str, Any], old: str | None,
                         new: str | None) -> None: ...
    def record(self, entry: dict[str, Any]) -> dict[str, Any]: ...
    def rehydrate(self, state: dict[str, Any], work_id: str) -> dict[str, Any] | None: ...
    def rehydrate_invocation(self, state: dict[str, Any], inv_id: str) -> dict[str, Any] | None: ...


class DispatchPort(Protocol):
    """What other collaborators use of ``Dispatch`` (M4-A): every dispatch route decides through it."""

    def decide_in(self, ctx: TxnContext, entrypoint: str, work_id: str, **args: Any) -> DispatchDecision: ...


class HistoryCommandsPort(Protocol):
    """What other collaborators use of ``HistoryCommands``."""

    def audit_backlog(self, state: dict[str, Any]) -> int | None: ...
    def audit_status(self, state: dict[str, Any]) -> dict[str, Any] | None: ...
