import {URL} from 'node:url';
import {spawn} from 'node:child_process';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
const out=process.env.W06_BROWSER_OUTPUT??'output/playwright-w06',ports={http:process.env.W06_HTTP_PORT??'4280',worker:process.env.W06_WORKER_PORT??'4281'};
fs.mkdirSync(out,{recursive:true});const children=[],checks=[],measurements=[];let browser;
function serve(mode){const log=fs.openSync(`${out}/${mode}-server.log`,'w');const child=spawn(process.execPath,mode==='http'?['--experimental-strip-types','scripts/demo-server.mjs']:['node_modules/vite/bin/vite.js','preview','--mode','demo','--host','127.0.0.1','--port',ports.worker,'--strictPort'],{env:{...process.env,DASHBOARD_PORT:ports.http},stdio:['ignore',log,log]});children.push(child);return child;}
async function ready(mode,child){for(let i=0;i<100;i++){if(child.exitCode!==null)throw Error(`Owned ${mode} server exited`);try{if((await globalThis.fetch(`http://127.0.0.1:${ports[mode]}`)).ok)return;}catch{/* Startup */}await new Promise(r=>globalThis.setTimeout(r,100));}throw Error('Server startup timeout');}
async function check(name,mode,run,phone=false){if(process.env.W06_BROWSER_FILTER&&!name.includes(process.env.W06_BROWSER_FILTER))return;const context=await browser.newContext({viewport:phone?{width:390,height:844}:{width:1440,height:1000},serviceWorkers:mode==='http'?'block':'allow',permissions:['clipboard-read','clipboard-write']}),page=await context.newPage(),requests=[],errors=[];page.on('request',r=>requests.push({url:r.url(),method:r.method(),etag:r.headers()['if-none-match']}));page.on('pageerror',e=>errors.push(e.message));await context.tracing.start({screenshots:true,snapshots:true});try{await run(page,`http://127.0.0.1:${ports[mode]}`,requests);assert.deepEqual(errors,[]);assert(requests.every(r=>['GET','HEAD'].includes(r.method)));if(mode==='http'){assert.equal(context.serviceWorkers().length,0);assert(!requests.some(r=>/mockServiceWorker|assets\/browser-/.test(r.url)));}checks.push({name,mode,phone,result:'PASS'});console.log(`PASS ${mode} ${phone?'phone':'desktop'} ${name}`);await context.tracing.stop();}catch(e){await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`${out}/failure-${checks.length}.png`,fullPage:true});await context.tracing.stop({path:`${out}/failure-${checks.length}.zip`});throw e;}finally{await context.close();}}
const route='/execution?fixture=F1&execution_trace=TRACE-Clangd';
async function pick(page,id){await page.locator(`[data-execution-pick="${id}"]`).click();await page.getByRole('heading',{name:id,exact:true}).waitFor();await page.getByRole('heading',{name:'Captured execution',exact:true}).waitFor();}
try{
 const http=serve('http'),worker=serve('worker');await Promise.all([ready('http',http),ready('worker',worker)]);browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH??'artifacts/playwright/browsers/chromium-1217/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});
 for(const mode of ['http','worker'])for(const phone of [false,true])await check('Clangd investigation, source identity, Evidence/packet navigation and restored focus',mode,async(page,base,requests)=>{
  await page.goto(base+route);await pick(page,'EV-03');if(!phone)assert.equal(await page.evaluate(()=>document.activeElement?.getAttribute('data-execution-pick')),'EV-03');else assert.equal(await page.evaluate(()=>document.activeElement?.textContent),'EV-03');
  await page.getByRole('link',{name:'Inspect evidence CLANGD-E871'}).click();await page.getByRole('button',{name:'ES-Removal',exact:true}).click();await page.getByRole('tab',{name:'Artifacts',exact:true}).click();await page.getByRole('button',{name:/^ART-Removal ·/}).click();await page.getByText(/undefined reference to dispatch_protocol/).waitFor();await page.getByRole('button',{name:'Back to originating investigation'}).click();await page.waitForURL(/\/execution\?/);await page.waitForFunction(()=>document.activeElement?.getAttribute('data-evidence-reference')==='REF-EXEC-Failure');
  await page.getByRole('button',{name:'Next recorded event'}).click();await page.getByRole('heading',{name:'EV-04',exact:true}).waitFor();await page.getByRole('button',{name:'Next recorded event'}).click();await page.getByRole('button',{name:'Inspect packet PKT-Retry',exact:true}).click();await page.getByRole('heading',{name:'Context packet PKT-Retry'}).waitFor();await page.getByText(/Supplied fixture excerpt only/).first().waitFor();assert.equal(await page.getByText('J-05',{exact:true}).count(),0);
  const concealed=requests.filter(r=>r.url.includes('/api/preview/execution/')).length;await page.getByRole('tab',{name:'Receipts',exact:true}).click();await page.getByText('No benefit evaluation supplied.',{exact:true}).waitFor();await page.getByText('RECEIPT-Retry-DELIVERY',{exact:true}).waitFor();await page.waitForTimeout(11000);assert.equal(requests.filter(r=>r.url.includes('/api/preview/execution/')).length,concealed);
  await page.getByRole('button',{name:'Back to recorded execution'}).click();await page.getByRole('heading',{name:'EV-05',exact:true}).waitFor();await page.waitForFunction(()=>document.activeElement?.getAttribute('data-execution-locator')==='LOC-RetryPacket');await page.getByRole('tab',{name:'Controls',exact:true}).click();await page.getByText('No enforcement result supplied.',{exact:true}).waitFor();await page.getByRole('tab',{name:'Validation receipts',exact:true}).click();await page.getByRole('heading',{name:'CTRL-RETRY-1 · filesystem',exact:true}).waitFor();await page.getByRole('tab',{name:'Provenance',exact:true}).click();await page.getByText('CLANGD-D42',{exact:true}).waitFor();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`${out}/${mode}-${phone?'phone':'desktop'}-story.png`,fullPage:true});
  await page.getByRole('tab',{name:'Details',exact:true}).click();await page.getByRole('button',{name:'Copy dashboard link',exact:true}).click();const copied=await page.evaluate(()=>navigator.clipboard.readText());assert.equal(new URL(copied).searchParams.get('execution_selected'),'EV-05');await page.goto(copied);await page.getByRole('heading',{name:'EV-05',exact:true}).waitFor();await page.getByRole('heading',{name:'Captured execution',exact:true}).waitFor();const before=requests.filter(r=>r.url.includes('/api/preview/execution/')).length;await page.waitForTimeout(11000);assert.equal(requests.filter(r=>r.url.includes('/api/preview/execution/')).length,before,'All W06 reads manual-only');
 },phone);
 for(const mode of ['http','worker'])await check('Typed fanout keeps correlation separate and controls distinct',mode,async(page,base)=>{
  await page.goto(base+route+'&execution_view=fanout&execution_case=cycles');await page.getByRole('button',{name:'Expand EX-Removal',exact:true}).click();await page.getByText(/EX-Removal ↔ EX-Discovery/).waitFor();assert.equal(await page.getByRole('button',{name:'Expand EX-Discovery',exact:true}).count(),0);await page.getByRole('button',{name:'Expand EX-Retry',exact:true}).click();await page.getByText('process spawned process',{exact:true}).waitFor();await page.getByRole('button',{name:'Expand EX-Helper',exact:true}).click();await page.getByText(/Cycle reference/).waitFor();await page.getByRole('button',{name:'Inspect EX-Retry',exact:true}).click();await page.getByRole('tab',{name:'Controls',exact:true}).click();await page.getByText('No enforcement result supplied.',{exact:true}).waitFor();assert.equal(await page.getByText('No validation receipt supplied.',{exact:true}).count(),0);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`${out}/${mode}-fanout.png`,fullPage:true});
 });
 for(const mode of ['http','worker'])await check('50-row paging, selection and bounded DOM replacement',mode,async(page,base,requests)=>{
  const start=Date.now();await page.goto(base+route+'&execution_case=large&execution_display=table');const results=page.getByRole('region',{name:'Recorded results'});await page.locator('.execution-table tbody tr').first().waitFor();assert.equal(await page.locator('.execution-table tbody tr').count(),50);await pick(page,'EV-03');const dom=await page.locator('*').count();await results.getByRole('button',{name:'Next page',exact:true}).click();await page.getByText(/Selected event is outside the current results/).waitFor();assert.equal(await page.locator('.execution-table tbody tr').count(),50);assert(await page.locator('*').count()<dom+20);measurements.push({mode,rows:50,dom_before:dom,dom_after:await page.locator('*').count(),requests:requests.filter(r=>r.url.includes('/api/preview/execution/')).length,duration_ms:Date.now()-start,fixture_events:189});await page.reload();await page.getByRole('heading',{name:'EV-03',exact:true}).waitFor();
 });
 await check('Unknown, missing, stale, mismatched and refused projections','http',async(page,base)=>{
  for(const name of ['denied','historical-unavailable','malformed']){await page.goto(base+route+'&execution_case='+name);await page.getByRole('alert').first().waitFor();}
  await page.goto(base+route+'&execution_case=unknown&execution_selected=EV-01');await page.locator('.unknown code:visible').filter({hasText:'FUTURE_LANE'}).first().waitFor();await page.getByRole('tab',{name:'Controls',exact:true}).click();await page.getByText('UNKNOWN',{exact:true}).first().waitFor();
  await page.goto(base+route+'&execution_case=missing&execution_selected=EV-05&execution_tab=controls');await page.getByRole('tab',{name:'Validation receipts',exact:true}).click();await page.getByText('No validation receipt supplied.',{exact:true}).waitFor();
  await page.goto(base+route+'&execution_case=mismatch&execution_selected=EV-05&execution_tab=controls');await page.getByRole('tab',{name:'Validation receipts',exact:true}).click();await page.getByRole('alert').waitFor();assert.equal(await page.getByText('CTRL-RETRY-1',{exact:false}).count(),0);
  await page.goto(base+route+'&execution_case=stale&execution_selected=EV-05&execution_tab=controls');await page.getByRole('tab',{name:'Validation receipts',exact:true}).click();await page.getByText('STALE SUPPLIED',{exact:true}).waitFor();
 });
 await check('Failed refresh retains valid data; refusal clears owned data and validators','http',async(page,base,requests)=>{
  await page.goto(base+route+'&execution_case=refresh-error');await page.getByRole('button',{name:'Refresh fixed trace'}).click();await page.getByText(/STALE \/ DISCONNECTED/).waitFor();await page.getByRole('button',{name:'EV-01',exact:true}).waitFor();
  await page.goto(base+route+'&execution_selected=EV-01');await page.getByRole('heading',{name:'Captured execution',exact:true}).waitFor();await page.route('**/api/preview/execution/**/events?**',r=>r.fulfill({status:403,body:''}));await page.getByRole('button',{name:'Refresh event page'}).click();await page.getByText(/Access unavailable \(403\)/).first().waitFor();assert.equal(await page.getByRole('heading',{name:'Captured execution',exact:true}).count(),0);await page.unroute('**/api/preview/execution/**/events?**');await page.getByRole('button',{name:/Retry/}).first().click();await page.getByRole('button',{name:'EV-01',exact:true}).waitFor();const reads=requests.filter(r=>r.url.includes('/traces/TRACE-Clangd/events?'));assert(!reads.at(-1).etag);
 });
 await check('Conditional manual refresh, historical firewall and explicit trace choice','http',async(page,base,requests)=>{
  await page.goto(base+'/execution?fixture=F1&execution_invocation=CLANGD-INV-Retry&execution_run=CLANGD-R-A2-4');await page.getByRole('button',{name:'Select TRACE-Clangd'}).waitFor();assert.equal(await page.getByRole('button',{name:'Select TRACE-Alternate'}).count(),1);assert(!requests.some(r=>/\/traces\/TRACE-/.test(r.url)));await page.getByRole('button',{name:'Select TRACE-Clangd'}).click();await page.getByRole('button',{name:'Refresh fixed trace'}).click();assert(requests.some(r=>/\/traces\/TRACE-Clangd\?/.test(r.url)&&r.etag));const before=requests.length;await page.goto(base+route+'&snapshot=unsupported');await page.getByRole('alert').first().waitFor();assert(!requests.slice(before).some(r=>r.url.includes('/api/preview/execution/')));
 });
 await check('Unexpected project/snapshot bindings and obsolete source replies','http',async(page,base)=>{
  await page.route('**/api/preview/execution/**/TRACE-Clangd?case=story',async r=>{const response=await r.fetch({headers:{...r.request().headers(),'if-none-match':''}}),body=await response.json();body.data.visibility_scope='unexpected-scope';await r.fulfill({response,json:body});});await page.goto(base+route);await page.getByRole('alert').first().waitFor();assert.equal(await page.getByRole('button',{name:'EV-01',exact:true}).count(),0);await page.unroute('**/api/preview/execution/**/TRACE-Clangd?case=story');
  await page.goto(base+route);await page.getByRole('button',{name:'EV-01',exact:true}).waitFor();await page.route('**/api/preview/execution/**/TRACE-Clangd?case=story',async r=>{const response=await r.fetch({headers:{...r.request().headers(),'if-none-match':''}}),body=await response.json();body.data.snapshot_id='REPLACED-SNAPSHOT';await r.fulfill({response,json:body});});await page.getByRole('button',{name:'Refresh fixed trace'}).click();await page.getByRole('alert').first().waitFor();assert.equal(await page.getByText('REPLACED-SNAPSHOT',{exact:true}).count(),0);await page.unroute('**/api/preview/execution/**/TRACE-Clangd?case=story');
  let delayed=false;await page.route('**/api/preview/execution/**/TRACE-Clangd?case=story',async r=>{delayed=true;const response=await r.fetch();await new Promise(resolve=>globalThis.setTimeout(resolve,400));try{await r.fulfill({response});}catch{/* Departed request is canceled. */}});await page.goto(base+route);while(!delayed)await page.waitForTimeout(10);await page.goto(base+route.replace('TRACE-Clangd','TRACE-Alternate')+'&execution_selected=EV-03');await page.getByRole('heading',{name:'Captured execution',exact:true}).waitFor();await page.waitForTimeout(500);assert.equal(await page.getByText('TRACE-Clangd',{exact:true}).count(),0);await page.getByText('TRACE-SNAP-2',{exact:true}).first().waitFor();
 });
 await check('Concealed shared Controls make no reads; source selection is explicit','http',async(page,base,requests)=>{
  await page.goto(base+'/compare?fixture=F1&a_source=SRC-Removal&b_source=SRC-Retry');await page.getByRole('button',{name:'Refresh B',exact:true}).waitFor();assert(!requests.some(r=>r.url.includes('/api/preview/execution/')));await page.getByText('Supplied execution controls · provisional preview',{exact:true}).last().click();await page.getByLabel('Choose fixed trace').selectOption('TRACE-Clangd');await page.getByLabel('Choose execution').selectOption('EX-Retry');await page.getByText('No enforcement result supplied.',{exact:true}).waitFor();
 });
 await check('Execution table off-page selection and list-focus restoration','http',async(page,base)=>{
  await page.goto(base+route+'&execution_case=large&execution_view=fanout&execution_display=table&execution_kind=executions&execution_selected=EX-Removal');await page.getByText(/Selected execution is outside the current results/).waitFor();await page.getByRole('heading',{name:'EX-Removal',exact:true}).waitFor();const row=page.locator('.execution-table tbody tr').first().getByRole('button'),id=await row.textContent();await row.click();await page.getByRole('heading',{name:id,exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.activeElement?.getAttribute('data-execution-pick')),id);await page.getByRole('button',{name:'Close detail',exact:true}).click();await page.waitForFunction(id=>document.activeElement?.getAttribute('data-execution-pick')===id,id);
 });
 await check('Disclosed Controls execution-list failure is explicit and recoverable','http',async(page,base)=>{
  await page.route('**/api/preview/execution/**/TRACE-Clangd/executions?case=story',r=>r.fulfill({status:503,body:''}));await page.goto(base+'/compare?fixture=F1&a_source=SRC-Removal&b_source=SRC-Retry');await page.getByRole('button',{name:'Refresh B',exact:true}).waitFor();await page.getByText('Supplied execution controls · provisional preview',{exact:true}).last().click();await page.getByLabel('Choose fixed trace').selectOption('TRACE-Clangd');await page.getByRole('alert').waitFor();assert.equal(await page.getByLabel('Choose execution').locator('option').count(),1);await page.unroute('**/api/preview/execution/**/TRACE-Clangd/executions?case=story');await page.getByRole('button',{name:'Retry',exact:true}).click();await page.getByLabel('Choose execution').selectOption('EX-Retry');await page.getByText('No enforcement result supplied.',{exact:true}).waitFor();
 });
 for(const phone of [false,true])await check('Keyboard tabs, long/hostile text, dark theme and 200% zoom','http',async(page,base)=>{
  await page.goto(base+route+'&execution_case=hostile&execution_selected=EV-01');await page.getByRole('heading',{name:'Captured execution',exact:true}).waitFor();await page.getByRole('tab',{name:'Details',exact:true}).focus();for(const [key,id] of [['ArrowRight','controls'],['End','provenance'],['Home','details']]){await page.keyboard.press(key);await page.waitForFunction(id=>document.activeElement?.id===`execution-detail-tab-${id}`,id);}assert.equal(await page.evaluate(()=>globalThis.w06Attack),undefined);assert.equal(await page.locator('img[src*="attacker.invalid"]').count(),0);await page.evaluate(()=>{document.documentElement.dataset.theme='dark';});await page.setViewportSize({width:phone?195:720,height:phone?422:500});await page.waitForTimeout(100);const geometry=await page.evaluate(()=>({viewport:window.innerWidth,scroll:document.documentElement.scrollWidth,overflow:[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>window.innerWidth+1).slice(0,20).map(e=>({tag:e.tagName,class:e.className,right:e.getBoundingClientRect().right,width:e.getBoundingClientRect().width}))}));assert(geometry.scroll<=geometry.viewport+1,JSON.stringify(geometry));await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`${out}/${phone?'phone':'desktop'}-dark-zoom.png`,fullPage:true});
 },phone);
 for(const mode of ['http','worker'])for(const width of [390,720])await check(`Responsive tables are reachable and story provenance conforms (${width}px)`,mode,async(page,base)=>{
  await page.setViewportSize({width,height:844});
  for(const view of ['events','fanout']){
   await page.goto(base+route+`&execution_view=${view}&execution_display=table`);
   const buttons=page.locator('.execution-table [data-execution-pick]');await buttons.first().waitFor();
   const identities=await buttons.evaluateAll(nodes=>nodes.map(n=>n.getAttribute('data-execution-pick')));
   for(const identity of identities){
    const button=page.locator(`[data-execution-pick="${identity}"]`);await button.scrollIntoViewIfNeeded();
    assert(await button.evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}),`${width}px ${view} ${identity} hit target`);
    await button.click();await page.getByRole('heading',{name:identity,exact:true}).waitFor();await page.getByRole('tab',{name:'Details',exact:true}).click();await page.getByRole('heading',{name:'Captured execution',exact:true}).waitFor();
    await page.getByRole('tab',{name:'Provenance',exact:true}).click();
    assert.equal(await page.locator('.unknown:visible').count(),0,'Story has no unknown semantic values');
    await page.getByRole('button',{name:'Close detail',exact:true}).click();
   }
   await page.waitForFunction(count=>document.querySelectorAll('.execution-table [data-execution-pick]').length===count,identities.length);
   const geometry=await page.locator('.execution-table td').evaluateAll(cells=>cells.map(el=>({height:el.getBoundingClientRect().height,content:el.scrollHeight,width:el.clientWidth,scroll:el.scrollWidth})));
   assert(geometry.length&&geometry.every(c=>c.content<=c.height+1&&c.scroll<=c.width+1),'Stacked cells contain their complete wrapped content');
   await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`${out}/${mode}-${width}-${view}-table.png`,fullPage:true});
  }
 },true);
 await check('Copied Controls receipt tab and deep packet return state','http',async(page,base)=>{
  await page.goto(base+route+'&execution_selected=EV-05&execution_tab=controls');
  await page.getByRole('tab',{name:'Validation receipts',exact:true}).click();await page.getByRole('heading',{name:'CTRL-RETRY-1 · filesystem',exact:true}).waitFor();
  await page.getByRole('button',{name:'Copy dashboard link',exact:true}).click();const copied=await page.evaluate(()=>navigator.clipboard.readText());assert.equal(new URL(copied).searchParams.get('execution_control_tab'),'receipts');
  await page.goto(copied);await page.getByRole('heading',{name:'CTRL-RETRY-1 · filesystem',exact:true}).waitFor();assert.equal(await page.getByRole('tab',{name:'Validation receipts',exact:true}).getAttribute('aria-selected'),'true');
  await page.goto(base+route+'&execution_selected=EV-05&execution_locator=LOC-RetryPacket&packet_tab=receipts');await page.getByText('RECEIPT-Retry-DELIVERY',{exact:true}).waitFor();await page.getByRole('button',{name:'Back to recorded execution',exact:true}).click();await page.getByRole('heading',{name:'EV-05',exact:true}).waitFor();assert.equal(new URL(page.url()).searchParams.has('packet_tab'),false);
 });
 fs.writeFileSync(`${out}/result.json`,JSON.stringify({checks,measurements,independent_review:'PENDING; implementer automation is not independent acceptance.'},null,2)+'\n');
}finally{await browser?.close();children.forEach(c=>c.kill('SIGTERM'));}
