import { spawn } from 'node:child_process';
import { URL } from 'node:url';
import { chromium } from 'playwright';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const out=process.env.W05_BROWSER_OUTPUT??'output/playwright-w05',httpPort=process.env.W05_HTTP_PORT??'4270',workerPort=process.env.W05_WORKER_PORT??'4271';
fs.mkdirSync(out,{recursive:true});const children=[],checks=[],measurements=[];let browser;
function server(port,args){const log=fs.openSync(`${out}/server-${port}.log`,'w'),child=spawn(process.execPath,args,{env:{...process.env,DASHBOARD_PORT:port},stdio:['ignore',log,log]});children.push(child);return child;}
const http=server(httpPort,['--experimental-strip-types','scripts/demo-server.mjs']),worker=server(workerPort,['node_modules/vite/bin/vite.js','preview','--mode','demo','--host','127.0.0.1','--port',workerPort,'--strictPort']);
async function ready(port,child){for(let i=0;i<100;i++){if(child.exitCode!==null)throw new Error('Owned server exited');try{if((await globalThis.fetch(`http://127.0.0.1:${port}`)).ok)return;}catch{/* Startup */}await new Promise(r=>globalThis.setTimeout(r,100));}throw new Error('Server startup failed');}
async function check(name,mode,run,phone=false){const context=await browser.newContext({viewport:phone?{width:390,height:844}:{width:1440,height:1000},serviceWorkers:mode==='http'?'block':'allow',permissions:['clipboard-read','clipboard-write']}),page=await context.newPage(),requests=[],errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push({url:r.url(),method:r.method(),etag:r.headers()['if-none-match']}));await context.tracing.start({screenshots:true,snapshots:true});try{await run(page,`http://127.0.0.1:${mode==='http'?httpPort:workerPort}`,requests);assert.deepEqual(errors,[]);assert(requests.every(r=>['GET','HEAD'].includes(r.method)));if(mode==='http'){assert.equal(context.serviceWorkers().length,0);assert(!requests.some(r=>/mockServiceWorker|assets\/browser-/.test(r.url)));}checks.push({name,mode,phone,result:'PASS'});console.log(`PASS ${mode} ${phone?'phone':'desktop'} ${name}`);await context.tracing.stop();}catch(error){await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`${out}/failure-${checks.length}.png`,fullPage:true});await context.tracing.stop({path:`${out}/failure-${checks.length}.zip`});throw error;}finally{await context.close();}}
const inspector='/evidence/inspect?fixture=F1';
async function artifact(page,id){await page.getByRole('tab',{name:'Artifacts',exact:true}).click();await page.getByRole('button',{name:new RegExp('^'+id+' ·')}).click();await page.getByText(/Excerpt SHA-256 verified:/).waitFor();}
try{
  await ready(httpPort,http);await ready(workerPort,worker);browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH??'artifacts/playwright/browsers/chromium-1217/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});
  for(const mode of ['http','worker'])for(const phone of [false,true])await check('Journal support/counterevidence, citation and origin restoration',mode,async(page,base,requests)=>{
    await page.goto(base+'/knowledge?fixture=F1&selected=J-05&panel=evidence');
    const link=page.getByRole('link',{name:/CLANGD-E871/});await link.click();await page.getByRole('button',{name:'ES-Removal',exact:true}).click();await artifact(page,'ART-Removal');await page.getByText(/undefined reference to dispatch_protocol/).waitFor();
    await page.getByRole('button',{name:'Copy citation',exact:true}).click();await page.getByText('Pinned citation copied.',{exact:true}).waitFor();const copied=await page.evaluate(()=>navigator.clipboard.readText());assert(copied.includes('Evidence: CLANGD-E871'));assert(copied.includes('Artifact: ART-Removal'));assert(copied.includes('Artifact revision: 1'));assert(!copied.includes('[fictional build]'));const pinned=copied.split('Pinned link: ')[1];assert(new URL(pinned).searchParams.get('evidence_artifact')==='ART-Removal');
    await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`${out}/${mode}-${phone?'phone':'desktop'}-reader.png`,fullPage:true});
    await page.getByRole('button',{name:'Back to originating investigation'}).click();await page.waitForURL(/\/knowledge\?/);await page.waitForFunction(()=>document.activeElement?.getAttribute('data-evidence-reference')==='REF-J05-CLANGD-E871');
    await page.getByRole('link',{name:/CLANGD-E880/}).click();await page.getByRole('button',{name:'ES-Counter',exact:true}).click();await artifact(page,'ART-Counter');await page.getByText(/This limits the lesson/).waitFor();await page.getByRole('tab',{name:'Provenance',exact:true}).click();await page.getByText('CLANGD-D42',{exact:true}).waitFor();
    await page.goto(pinned);await page.getByText(/undefined reference to dispatch_protocol/).waitFor();const before=requests.filter(r=>r.url.includes('/api/preview/evidence/')).length;await page.waitForTimeout(11000);assert.equal(requests.filter(r=>r.url.includes('/api/preview/evidence/')).length,before,'Fixed sources/excerpts have no interval reads');
    await page.getByRole('button',{name:'Refresh excerpt',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('[role="status"]')?.textContent?.includes('Loading'));assert(requests.some(r=>r.url.includes('/excerpt?')&&r.etag),'Conditional request used');
  },phone);
  for(const mode of ['http','worker'])await check('Packet association maps exact source/snapshot and restores packet',mode,async(page,base,requests)=>{
    await page.goto(base+'/compare?fixture=F1&a_source=SRC-Removal&b_source=SRC-Retry&packet=PKT-Retry&packet_side=b');await page.getByRole('link',{name:'CLANGD-E875',exact:true}).click();await page.getByRole('button',{name:'ES-Discovery',exact:true}).click();await artifact(page,'ART-Discovery');await page.getByText(/Generated caller now appears/).waitFor();assert.equal(new URL(page.url()).searchParams.get('evidence_reference'),'REF-PKT-Retry-E875');const concealed=requests.filter(r=>r.url.includes('/api/preview/investigation/')).length;await page.waitForTimeout(11000);assert.equal(requests.filter(r=>r.url.includes('/api/preview/investigation/')).length,concealed);await page.getByRole('button',{name:'Back to originating investigation'}).click();await page.waitForURL(/\/compare\?/);await page.waitForFunction(()=>document.activeElement?.getAttribute('data-evidence-reference')==='REF-PKT-Retry-E875');
  });
  for(const mode of ['http','worker'])await check('Bounded artifact/excerpt pages preserve selection and exact artifact identity',mode,async(page,base,requests)=>{
    const started=Date.now();await page.goto(base+inspector+'&evidence_case=large&evidence_source=ES-Removal&evidence_tab=artifacts');const list=page.locator('.evidence-panes > section').first();await list.locator('tbody tr').first().waitFor();assert.equal(await list.locator('tbody tr').count(),50);const domBefore=await page.locator('*').count();await page.getByRole('button',{name:/^ART-000 ·/}).click();await page.getByText(/Excerpt SHA-256 verified:/).waitFor();const detail=page.locator('.evidence-panes > section').nth(1);await detail.getByRole('button',{name:'Next page',exact:true}).click();await page.getByText(/Bytes \[163/).waitFor();await list.getByRole('button',{name:'Next page',exact:true}).click();await page.getByRole('button',{name:/^ART-050 ·/}).waitFor();assert.equal(await list.locator('tbody tr').count(),50);await page.getByText(/outside the displayed page/).waitFor();measurements.push({mode,rows_before:50,rows_after:50,dom_before:domBefore,dom_after:await page.locator('*').count(),requests:requests.filter(r=>r.url.includes('/api/preview/evidence/')).length,duration_ms:Date.now()-started});await page.reload();await page.getByText(/Excerpt SHA-256 verified:/).waitFor();assert.equal(new URL(page.url()).searchParams.get('evidence_artifact'),'ART-000');
  });
  for(const scenario of ['denied','not-found','historical-unavailable','malformed','hash-mismatch','binding-mismatch'])await check('Explicit '+scenario+' result','http',async(page,base)=>{
    await page.goto(base+inspector+`&evidence_case=${scenario}&evidence_source=ES-Removal&evidence_tab=artifacts&evidence_artifact=ART-Removal&evidence_revision=1`);await page.getByRole('alert').first().waitFor();assert.equal(await page.getByText(/Excerpt SHA-256 verified:/).count(),0);
  });
  await check('Hostile source controls, dark theme, zoom, keyboard tabs','http',async(page,base)=>{
    await page.goto(base+inspector+'&evidence_case=hostile&evidence_source=ES-Removal&evidence_tab=artifacts&evidence_artifact=ART-Removal&evidence_revision=1');await page.getByText(/Excerpt SHA-256 verified:/).waitFor();const source=await page.locator('.evidence-source').textContent();for(const marker of ['U+001B','U+202E','U+202C','U+200B','U+2066','U+2069'])assert(source.includes(marker));assert.equal(await page.evaluate(()=>globalThis.evidenceAttack),undefined);await page.evaluate(()=>{document.documentElement.dataset.theme='dark';document.documentElement.style.zoom='2';});await page.getByRole('tab',{name:'Artifacts',exact:true}).focus();await page.keyboard.press('End');await page.waitForFunction(()=>document.getElementById('evidence-tab-provenance')?.getAttribute('aria-selected')==='true');await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`${out}/dark-zoom.png`,fullPage:true});
  });
  await check('Missing/partial/unsupported/empty projections never fabricate contents','http',async(page,base,requests)=>{
    for(const [scenario,text] of [['missing','No artifact associations supplied.'],['partial','No artifact availability explanation supplied.'],['unknown','FUTURE_AVAILABILITY'],['unsupported','Unsupported media or encoding. No artifact body requested.']]){await page.goto(base+inspector+`&evidence_case=${scenario}&evidence_source=ES-Removal&evidence_tab=artifacts`);if(scenario!=='missing')await page.getByRole('button',{name:/^ART-Removal ·/}).click();await page.getByText(new RegExp(text.replaceAll('.','\\.'))).first().waitFor();}assert(!requests.some(r=>/case=(partial|unknown|unsupported)/.test(r.url)&&r.url.includes('/excerpt?')));await page.goto(base+inspector+'&evidence_case=empty');await page.getByText('No evidence sources supplied for these filters.',{exact:true}).waitFor();
  });
  await check('Failed refresh retains visibly marked valid excerpt','http',async(page,base)=>{
    await page.goto(base+inspector+'&evidence_case=refresh-error&evidence_source=ES-Removal&evidence_tab=artifacts&evidence_artifact=ART-Removal&evidence_revision=1');await page.getByText(/Excerpt SHA-256 verified:/).waitFor();await page.getByRole('button',{name:'Refresh excerpt',exact:true}).click();await page.getByText(/STALE \/ DISCONNECTED/).waitFor();await page.getByText(/undefined reference to dispatch_protocol/).waitFor();
  });
  await check('Refusal removes all owned source/excerpt representations','http',async(page,base,requests)=>{
    await page.goto(base+inspector+'&evidence_source=ES-Removal&evidence_tab=artifacts&evidence_artifact=ART-Removal&evidence_revision=1');await page.getByText(/Excerpt SHA-256 verified:/).waitFor();await page.route('**/api/preview/evidence/**/excerpt?**',route=>route.fulfill({status:403,body:'',headers:{'Content-Type':'application/json'}}));await page.getByRole('button',{name:'Refresh excerpt',exact:true}).click();await page.getByText(/Access unavailable \(403\)/).first().waitFor();assert.equal(await page.getByText(/Excerpt SHA-256 verified:/).count(),0);assert.equal(await page.getByText(/undefined reference to dispatch_protocol/).count(),0);await page.unroute('**/api/preview/evidence/**/excerpt?**');await page.getByRole('button',{name:/Retry/}).first().click();await page.getByText(/Excerpt SHA-256 verified:/).waitFor();const reads=requests.filter(r=>/\/sources\/ES-Removal\?/.test(r.url));assert(!reads.at(-1).etag,'Scope refusal cleared source validators too');
  });
  await check('Unsupported historical parameters stop preview reads','http',async(page,base,requests)=>{await page.goto(base+inspector+'&snapshot=unsupported');await page.getByText(/Historical snapshot reads are not supported by this contract/).waitFor();assert(!requests.some(r=>r.url.includes('/api/preview/evidence/')));});
  fs.writeFileSync(`${out}/result.json`,JSON.stringify({checks,measurements,independent_review:'PENDING; implementer automation is not independent acceptance.'},null,2)+'\n');
}finally{await browser?.close();for(const child of children)child.kill('SIGTERM');}
