import {spawn,execFileSync} from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const out=process.env.W06_MEASURE_OUTPUT??'output/w06-measurements',baseline=process.env.W06_BASELINE_WEB;
if(!baseline)throw Error('Set W06_BASELINE_WEB to the clean frozen W05 frontend directory.');
fs.mkdirSync(out,{recursive:true});const children=[],samples=[];let browser;
async function start(port,cwd,root){const log=fs.openSync(`${out}/server-${port}.log`,'w'),child=spawn(process.execPath,['--experimental-strip-types','scripts/demo-server.mjs'],{cwd,env:{...process.env,DASHBOARD_PORT:String(port),...(root?{DASHBOARD_STATIC_ROOT:root}:{})},stdio:['ignore',log,log]});children.push(child);const base=`http://127.0.0.1:${port}`;for(let i=0;i<100;i++){if(child.exitCode!==null)throw Error('Measurement server exited');try{if((await globalThis.fetch(base)).ok)return base;}catch{/* Startup */}await new Promise(r=>globalThis.setTimeout(r,100));}throw Error('Measurement startup timeout');}
try{
 const source=execFileSync('git',['rev-parse','HEAD'],{cwd:baseline,encoding:'utf8'}).trim();assert.equal(source,'da46807d4fb35ec742f042425c347cd480ba8f65');assert.equal(execFileSync('git',['status','--porcelain'],{cwd:baseline,encoding:'utf8'}),'');
 const [oldBase,newBase]=await Promise.all([start(4282,baseline,path.join(baseline,'artifacts/offline-gate/dist-demo')),start(4283,process.cwd())]);browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH??path.resolve('artifacts/playwright/browsers/chromium-1217/chrome-linux64/chrome'),args:['--no-sandbox']});
 const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});
 for(const [label,base,route,selector,population] of [['Frozen W05 artifact page',oldBase,'/evidence/inspect?fixture=F1&evidence_case=large&evidence_source=ES-Removal&evidence_tab=artifacts','.evidence-panes table tbody tr',126],['W06 recorded event page',newBase,'/execution?fixture=F1&execution_case=large&execution_trace=TRACE-Clangd&execution_display=table','.execution-table tbody tr',189]]){
  for(let i=0;i<3;i++){const page=await context.newPage(),requests=[],bodies=[],errors=[];page.on('request',r=>{if(r.url().includes('/api/'))requests.push(r.url());});page.on('response',r=>{if(r.url().includes('/api/'))bodies.push(r.body().then(b=>b.length));});page.on('pageerror',e=>errors.push(e.message));const started=Date.now();await page.goto(base+route);await page.locator(selector).first().waitFor();assert.equal(await page.locator(selector).count(),50);const sample={label,population,sample:i,warmup:i===0,render_ready_ms:Date.now()-started,rows:50,dom_nodes:await page.locator('*').count(),api_requests:requests.length,api_bytes:(await Promise.all(bodies)).reduce((a,b)=>a+b,0)};const first=await page.locator(selector).first().textContent();await page.getByRole('button',{name:'Next page',exact:true}).click();await page.waitForFunction(({selector,first})=>{const rows=document.querySelectorAll(selector);return rows.length===50&&rows[0].textContent!==first;},{selector,first});assert.deepEqual(errors,[]);sample.rows_after=await page.locator(selector).count();sample.dom_after=await page.locator('*').count();samples.push(sample);await page.close();}
 }
 await context.close();assert.equal(execFileSync('git',['status','--porcelain'],{cwd:baseline,encoding:'utf8'}),'');fs.writeFileSync(`${out}/result.json`,JSON.stringify({baseline_commit:source,samples,caveat:'Different workflows and fixture populations; one warmup and two warm samples. Bounded pages and request observations, not an improvement or timing SLA. Active result/detail/receipt queries are retired on identity/page changes; fanout holds at most24 nodes.'},null,2)+'\n');console.log(JSON.stringify(samples));
}finally{await browser?.close();children.forEach(c=>c.kill('SIGTERM'));}
