import { useMemo,useState } from 'react';
import { useProjection } from '../../../client/queries';
import { InvestigationTabs } from '../../../components/InvestigationTabs';
import { SemanticValue } from '../../../components/States';
import { JsonContent } from '../../../components/Content';
import { Pager } from '../../../components/ProjectionViews';
import { ErrorState,useControls } from '../investigation/ui';
import { executionSchemas,bindingIssue,executionIssue,type Trace } from './schema';
import { useExecutionPage,useExecutionReader,useTrace } from './session';
import { vocabularyInventory } from './vocabulary';
import type { ReadTransport } from '../../transport';
export function ControlsPresentation({trace,executionId,name,reader,shareActivity=false}:{trace:Trace;executionId:string;name:string;reader:ReadTransport;shareActivity?:boolean}){
 const {params,update}=useControls(),[localActivity,setLocalActivity]=useState('claims');
 const activity=shareActivity?(params.get('execution_control_tab')??'claims'):localActivity;
 const setActivity=(value:string)=>shareActivity?update({execution_control_tab:value,execution_receipt_cursor:null}):setLocalActivity(value);
 const route=`/traces/${trace.id}/executions/${executionId}`,schema=useMemo(()=>executionSchemas.ControlsResponse.superRefine(({data:c},ctx)=>{if(bindingIssue(c.binding,trace)||c.execution_id!==executionId||JSON.stringify(c.environment)!==JSON.stringify(trace.environment))ctx.addIssue({code:'custom',message:'Control execution/environment binding mismatch'});}),[trace,executionId]);
 const query=useExecutionPage(`${route}/controls?case=${name}`,schema,reader,activity==='claims');
 const receiptSchema=useMemo(()=>executionSchemas.ReceiptListResponse.superRefine(({data:v},ctx)=>{if(v.items.some(r=>bindingIssue(r.binding,trace)||r.execution_id!==executionId||JSON.stringify(r.environment)!==JSON.stringify(trace.environment)))ctx.addIssue({code:'custom',message:'Validation receipt execution/environment binding mismatch'});}),[trace,executionId]);
 const receipts=useExecutionPage(`${route}/receipts?`+new URLSearchParams({case:name,limit:'50',...(params.get('execution_receipt_cursor')?{cursor:params.get('execution_receipt_cursor')!}:{})}),receiptSchema,reader,activity==='receipts');
 const c=query.data?.value.data;
 return <section className="execution-controls" aria-label="Supplied controls"><p className="scope-note">Configured ≠ available ≠ authorized ≠ active ≠ successfully tested. Receipt absence does not prove validation never occurred. Fictional claims are not current Engine guarantees.</p>
 <InvestigationTabs prefix="execution-controls" label="Control activity" tabs={[{id:'claims',label:'Claims & budgets'},{id:'receipts',label:'Validation receipts'}]} active={activity} select={setActivity}/>
 <div role="tabpanel" id={`execution-controls-panel-${activity}`} aria-labelledby={`execution-controls-tab-${activity}`}>
 {activity==='claims'&&<>{query.error&&<ErrorState error={query.error} retry={()=>void query.refetch()}/>} {c?<><button onClick={()=>void query.refetch()}>Refresh control claims</button><p>Profile {c.profile_id??'UNKNOWN'} · Environment {c.environment.join(' · ')||'UNKNOWN'}</p>{!c.complete&&<p>Control projection is incomplete.</p>}<div className="table-scroll"><table className="execution-table" role="table"><thead role="rowgroup"><tr role="row"><th role="columnheader" scope="col">Dimension</th><th role="columnheader" scope="col">Configured</th><th role="columnheader" scope="col">Available</th><th role="columnheader" scope="col">Authorized</th><th role="columnheader" scope="col">Active</th><th role="columnheader" scope="col">Mechanism / self_test</th></tr></thead><tbody role="rowgroup">{c.dimensions.map(d=>{const known=vocabularyInventory.dimensions[d.name as keyof typeof vocabularyInventory.dimensions]??[];return <tr role="row" key={d.name}><td role="cell" data-label="Dimension"><SemanticValue value={d.name} known={Object.keys(vocabularyInventory.dimensions)}/><small>{d.vocabulary==='PROVISIONAL'?' PROVISIONAL':' Engine vocabulary'}</small></td>{(['configured','available','authorized','active'] as const).map(k=><td role="cell" data-label={k} key={k}><SemanticValue value={d[k]??'UNKNOWN'} known={[...known,'UNKNOWN']}/></td>)}<td role="cell" data-label="Mechanism / self_test">{d.mechanism??'UNKNOWN'} · {d.self_test?`ok: ${d.self_test.ok}; ${d.self_test.reason??'No reason supplied'}`:'No self_test supplied'}</td></tr>;})}</tbody></table></div><p>process_ownership is not a process-containment claim. os_readonly_roots describes filesystem integrity, not confidentiality or network isolation.</p>
 <h3>Supplied budget observations · PROVISIONAL</h3><p>These observations do not define a cost ledger, remaining budget, DispatchDecision or enforcement result. No count is inferred from loaded pages.</p>{c.budgets.length?c.budgets.map(b=><section className="panel" key={b.id}><h4>{b.id}</h4><dl><dt>Configured quantity / unit / policy</dt><dd>{b.quantity??'UNKNOWN'} {b.unit} · {b.policy_id??'UNKNOWN'}</dd><dt>Observed / active / unattributed</dt><dd>{b.observed??'UNKNOWN'} / {b.active??'UNKNOWN'} / {b.unattributed??'UNKNOWN'}</dd><dt>Supplied depth</dt><dd>{b.depth??'UNKNOWN'}</dd><dt>Measurement scope / completeness</dt><dd>{b.measurement_scope} · {b.complete?'Complete':'Incomplete'}</dd><dt>Reported enforcement</dt><dd>{b.reported_enforcement??'No enforcement result supplied.'}</dd><dt>Supplied source</dt><dd>{b.source.id}</dd></dl></section>):<p>No budget observations supplied.</p>}{query.error&&<p role="status">STALE / DISCONNECTED — displaying valid previous claims.</p>}</>:!query.error&&<p role="status">Loading controls…</p>}</>}
 {activity==='receipts'&&<>{receipts.error&&<ErrorState error={receipts.error} retry={()=>void receipts.refetch()}/>} {receipts.data?<><button onClick={()=>void receipts.refetch()}>Refresh validation receipts</button><p>Receipt result/currentness projection · PROVISIONAL. Age does not establish expiry or currentness.</p>{receipts.data.value.data.items.length?receipts.data.value.data.items.map(r=><section className="panel" key={r.id}><h3>{r.id} · {r.dimension}</h3><p><SemanticValue value={r.result} known={['REPORTED_TEST_PASS','REPORTED_TEST_FAIL','UNKNOWN']}/> · <SemanticValue value={r.currentness} known={['UNLABELED','STALE_SUPPLIED','UNKNOWN']}/></p><p>Validated UTC {r.validated_at??'Not supplied'} · {r.validated_at?`Age at trace capture: ${Math.floor((Date.parse(trace.captured_at)-Date.parse(r.validated_at))/1000)} seconds (no expiry rule)`:'Age unknown'}</p><p>Mechanism: {r.mechanism??'UNKNOWN'} · self_test: {r.self_test?`ok: ${r.self_test.ok}; ${r.self_test.reason??'No reason supplied'}`:'No self_test supplied'}</p><details><summary>Exact receipt binding and provenance</summary><JsonContent value={r}/></details></section>):<p>No validation receipt supplied.</p>}<Pager next={receipts.data.value.data.next_cursor} cursorKey="execution_receipt_cursor" resetKey={`${trace.id}:${executionId}:${name}`}/>{receipts.error&&<p role="status">STALE / DISCONNECTED — displaying valid previous receipts.</p>}</>:!receipts.error&&<p role="status">Loading receipts…</p>}</>}
 </div></section>;
}
/** Reusable disclosed host; source choice remains explicit outside the recorder too. */
export function ControlsDisclosure({invocation,run,displayed=true}:{invocation:string;run?:string|null;displayed?:boolean}){
 const [open,setOpen]=useState(false);
 return <details onToggle={e=>setOpen(e.currentTarget.open)}><summary>Supplied execution controls · provisional preview</summary>{open&&displayed&&<ControlsHost invocation={invocation} run={run}/>}</details>;
}
function ControlsHost({invocation,run}:{invocation:string;run?:string|null}){
 const [source,setSource]=useState(''),[selected,setSelected]=useState(''),chooser=useExecutionReader(`controls-chooser:${invocation}:${run??''}`,'story');
 const query=useProjection('/traces?'+new URLSearchParams({case:'story',invocation_id:invocation,...(run?{run_id:run}:{})}),executionSchemas.TraceListResponse,'history',chooser.ready,true,chooser.reader,false);
 const t=useTrace('story',source),trace=t.data?.value.data;
 const ownedSchema=useMemo(()=>executionSchemas.ExecutionListResponse.superRefine(({data:v},ctx)=>{if(!trace||v.items.some(e=>executionIssue(e,trace)))ctx.addIssue({code:'custom',message:'Control host execution binding mismatch'});}),[trace]);
 const rows=useProjection(`/traces/${source}/executions?case=story`,ownedSchema,'history',!!trace,true,t.reader,false);
 return <>{query.error&&<ErrorState error={query.error} retry={()=>void query.refetch()}/>}<label>Choose fixed trace<select value={source} onChange={e=>{setSource(e.target.value);setSelected('');}}><option value="">No trace selected</option>{query.data?.value.data.items.map(s=><option key={s.id} value={s.id}>{s.id} · {s.snapshot_id}</option>)}</select></label>{query.data&&!query.data.value.data.items.length&&<p>No trace association supplied.</p>}{t.error&&<ErrorState error={t.error} retry={()=>void t.refetch()}/>} {trace&&<>{rows.error&&<ErrorState error={rows.error} retry={()=>void rows.refetch()}/>} {rows.error&&rows.data&&<p role="status">STALE / DISCONNECTED — displaying previous execution associations.</p>}{rows.data&&!rows.data.value.data.items.some(e=>e.invocation?.id===invocation&&(!run||e.run_id===run))&&<p>No execution association supplied for this invocation/run.</p>}{!rows.data&&!rows.error&&<p role="status">Loading execution associations…</p>}<label>Choose execution<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">No execution selected</option>{rows.data?.value.data.items.filter(e=>e.invocation?.id===invocation&&(!run||e.run_id===run)).map(e=><option key={e.id}>{e.id}</option>)}</select></label>{selected&&<ControlsPresentation key={`${source}:${selected}`} trace={trace} executionId={selected} name="story" reader={t.reader}/>}</>}</>;
}
