import type { Trace,Event,Execution,Controls,ControlReceipt } from './schema';
// @ts-expect-error Pinned strip-types artifact runner.
import { investigationFixture } from '../investigation/fixtures.ts';
const ref=(id:string,kind='execution_reference',title:string|null=null)=>({id,kind,title});
export function executionFixture(name='story',project='aew-demo'){
  const previous=investigationFixture(),binding={source_id:'TRACE-Clangd',snapshot_id:'TRACE-SNAP-1',project_id:project};
  const t:Trace={id:binding.source_id,snapshot_id:binding.snapshot_id,captured_at:'2026-10-02T16:45:00Z',project_id:project,visibility_scope:project,work:ref('CLANGD-T181','work_reference'),root_execution:'EX-Removal',invocation_id:'CLANGD-INV-Removal',run_id:'CLANGD-R-A2-2',source_revision:'fictional-trace-1',environment:['Rocky 8','clangd 19'],coverage:['invocation','tools','evidence','reviews','transitions','context'].map(lane=>({lane,complete:lane!=='tools',gaps:lane==='tools'?[{id:'GAP-tools-1',explanation:'Tool recording was unavailable between supplied observations; no reconstructed events.',source:ref('RECORDER-1','recording_source')}]:[],explanation:lane==='tools'?'Incomplete supplied tool coverage.':null,retention:'FIXTURE_ONLY'})),execution_bindings:[],executions_complete:false,canonical_references:[ref('CLANGD-D42','decision_reference','Generated protocol definitions remain source-controlled')]};
  const executions:Execution[]=previous.sources.slice(0,2).map((s,i)=>({id:i?'EX-Retry':'EX-Removal',binding:{...binding},execution_class:'invocation',registration_state:'registered',invocation:s.invocation,run_id:s.invocation.runs[0].id,relations:[],relations_complete:false,references:[ref(s.id,'comparison_source')]}));
  executions.push({id:'EX-Discovery',binding:{...binding},execution_class:'invocation',registration_state:'registered',invocation:{...structuredClone(previous.sources[1].invocation),id:'CLANGD-INV-Discovery',created_at:'2026-10-02T16:25:00Z',runs:[{...previous.sources[1].invocation.runs[0],id:'CLANGD-R-A2-3',launched_at:'2026-10-02T16:26:00Z'}],summary:{format:'plain',text:'Refreshing the compilation database exposed generated callers.'}},run_id:'CLANGD-R-A2-3',relations:[],relations_complete:true,references:[]});
  executions.push({id:'EX-Helper',binding:{...binding},execution_class:'helper',registration_state:'unregistered',invocation:null,run_id:null,relations:[],relations_complete:false,references:[ref('PROCESS-17','process_reference')]});
  const addRelation=(from:string,to:string,kind:string,targetKind='execution')=>executions.find(e=>e.id===from)!.relations.push({id:`REL-${kind}-${to}`,relation_kind:kind,from:{id:from,kind:'execution'},to:{id:to,kind:targetKind},source:ref(`SOURCE-${kind}`,'relation_source'),provenance:[ref('RECORDER-1','recording_source')],binding:{...binding}});
  addRelation('EX-Removal','EX-Retry','registered_child_invocation');
  addRelation('EX-Retry','EX-Helper','harness_launched_helper');
  addRelation('EX-Retry','PROCESS-18','process_spawned_process','process');
  addRelation('EX-Retry','PROVIDER-19','provider_suboperation','provider_operation');
  addRelation('EX-Removal','EX-Discovery','trace_correlation');
  const specs=[['EV-01',1,'invocation','recorded_activity','Removal attempt started.','EX-Removal','16:16'],['EV-02',2,'tools','tool_reference','Removal broke generated protocol callers; change reverted.','EX-Removal','16:20'],['EV-03',3,'evidence','evidence_publication','Failure evidence CLANGD-E871 was published.','EX-Removal','16:20'],['EV-04',5,'evidence','evidence_publication','Compilation discovery CLANGD-E875: refreshed data reveals callers.','EX-Discovery','16:30'],['EV-05',6,'context','preparation','PKT-Retry prepared with discovery J-04 and CLANGD-E875; J-05 was not yet published.','EX-Retry','16:33'],['EV-06',7,'context','delivery','Delivery acknowledgment supplied for PKT-Retry.','EX-Retry','16:34'],['EV-07',8,'context','citation','Output cites CLANGD-E875; no benefit evaluation supplied.','EX-Retry','16:38'],['EV-08',9,'transitions','reported_transition','Corrected build passed; invocation record reports completion. No legal historical transition or causation inferred.','EX-Retry','16:38'],['EV-09',10,'reviews','review_reference','Canonical CLANGD-D42 remains authoritative; J-05 published afterward at 16:40 UTC.','EX-Retry','16:40']] as const;
  const events:Event[]=specs.map(([id,ordinal,lane,kind,summary,execution_id,at],index)=>{const e=executions.find(e=>e.id===execution_id)!;return{id,binding:{...binding},ordinal,source_at:`2026-10-02T${at}:00Z`,observed_at:null,lane,kind,summary,reasons:[],execution_id,invocation_id:e.invocation?.id??null,run_id:e.run_id,references:id==='EV-03'?[ref('CLANGD-E871','evidence_reference')]:id==='EV-04'?[ref('CLANGD-E875','evidence_reference')]:id==='EV-09'?t.canonical_references:[],locator_ids:id==='EV-03'?['LOC-Failure']:id==='EV-04'?['LOC-Discovery']:['EV-05','EV-06','EV-07'].includes(id)?['LOC-RetryPacket']:[],previous_id:index?specs[index-1][0]:null,next_id:index+1<specs.length?specs[index+1][0]:null};});
  const controls:Controls[]=executions.map(e=>({execution_id:e.id,binding:{...binding},environment:t.environment,profile_id:'fictional-investigation-v1',complete:false,dimensions:[{name:'filesystem',configured:'os_readonly_roots',available:'os_readonly_roots',authorized:null,active:e.id==='EX-Retry'?'os_readonly_roots':'workdir_separation_only',mechanism:e.id==='EX-Retry'?'fictional-linux-readonly':null,self_test:null,vocabulary:'ENGINE'},{name:'process_ownership',configured:'pid_namespace',available:'pid_namespace',authorized:null,active:e.id==='EX-Retry'?'pid_namespace':'process_group',mechanism:null,self_test:null,vocabulary:'ENGINE'},{name:'network',configured:'not_provided',available:'not_provided',authorized:null,active:'not_provided',mechanism:null,self_test:null,vocabulary:'ENGINE'}],budgets:[{id:`BUDGET-${e.id}`,policy_id:'fictional-fanout-v1',quantity:8,unit:'executions',measurement_scope:'Supplied trace-local recorder observation, not a global ledger.',observed:4,active:1,unattributed:1,depth:2,complete:false,reported_enforcement:null,source:ref('BUDGET-SOURCE-1','observation_source')}]}));
  const receipts:ControlReceipt[]=[{id:'CTRL-RETRY-1',execution_id:'EX-Retry',binding:{...binding},environment:t.environment,dimension:'filesystem',result:'REPORTED_TEST_PASS',currentness:'UNLABELED',validated_at:'2026-10-02T16:32:00Z',mechanism:'fictional-linux-readonly',self_test:{ok:true,reason:null},provenance:[ref('FICTIONAL-PROBE-1','validation_source')]}];
  if(name==='large'){for(let i=0;i<180;i++){events.push({...structuredClone(events[0]),id:`EV-L-${String(i).padStart(4,'0')}`,ordinal:20+i,previous_id:null,next_id:null});executions.push({...structuredClone(executions[3]),id:`EX-L-${String(i).padStart(4,'0')}`,relations:[]});}for(let i=0;i<110;i++)receipts.push({...structuredClone(receipts[0]),id:`CTRL-L-${String(i).padStart(4,'0')}`});}
  if(name==='fanout'){controls[1].budgets[0].observed=27;controls[1].budgets[0].active=11;controls[1].budgets[0].reported_enforcement=null;}
  if(name==='cycles')addRelation('EX-Helper','EX-Removal','registered_child_invocation');
  if(name==='unordered'){events[2].source_at='2026-10-02T15:00:00Z';events[1].ordinal=null;}
  if(name==='unknown'){t.coverage[0].lane='FUTURE_LANE';events[0].lane='FUTURE_LANE';events[0].kind='FUTURE_EVENT';executions[1].relations[0].relation_kind='FUTURE_RELATION';controls[1].dimensions.push({...controls[1].dimensions[0],name:'future_guarantee',active:'FUTURE_VALUE',vocabulary:'PROVISIONAL'});}
  if(name==='missing'){receipts.splice(0);controls.forEach(c=>{c.dimensions.forEach(d=>{d.active=null;d.available=null;});c.budgets=[];});}
  if(name==='stale')receipts[0].currentness='STALE_SUPPLIED';
  if(name==='mismatch')receipts[0].binding.snapshot_id='WRONG-SNAPSHOT';
  if(name==='malformed')(events[0] as unknown as Record<string,unknown>).raw_prompt='excluded';
  if(name==='hostile')events[0].summary='<script>globalThis.w06Attack=true</script>\n[unsafe](javascript:alert(1))\n<img src="https://attacker.invalid/w06">';
  if(name==='partial')t.coverage.forEach(c=>c.complete=false);
  t.execution_bindings=executions.map(e=>({execution_id:e.id,invocation_id:e.invocation?.id??null,run_id:e.run_id}));
  const traces=name==='empty'?[]:[t,{...structuredClone(t),id:'TRACE-Alternate',snapshot_id:'TRACE-SNAP-2',root_execution:'EX-Removal'}];
  if(name==='large')for(let i=0;i<120;i++)traces.push({...structuredClone(t),id:`TRACE-L-${String(i).padStart(4,'0')}`,snapshot_id:`TRACE-SNAP-L-${i}`});
  return {traces,events,executions,controls,receipts};
}
