import { useDashboard } from '../../../client/dashboard';
import { useEffect,useLayoutEffect,useMemo,useRef,useState } from 'react';
import { Link,useLocation,useNavigate } from 'react-router-dom';
import manifest from '../../../../docs/design/execution-fixtures.manifest.json';
import { InvestigationTabs,focusBelowHeader } from '../../../components/InvestigationTabs';
import { CopyDashboardLink } from '../../../components/CopyDashboardLink';
import { SourceStrip } from '../../../components/Investigation';
import { Pager,Reasons } from '../../../components/ProjectionViews';
import { ContextReferences } from '../investigation/ContextReferences';
import { SafeContent,JsonContent } from '../../../components/Content';
import { SemanticValue } from '../../../components/States';
import { invocationStatuses,invocationRoles,harnessStatuses } from '../../vocabulary';
import { historicalRequested } from '../../navigation';
import { id } from '../../schema';
import { ErrorState,useControls } from '../investigation/ui';
import { useComparisonSource } from '../investigation/session';
import { PacketInspector,packetTabs } from '../investigation/PacketInspector';
import { EvidenceReference } from '../evidence/Reference';
import { inspectionAssociations } from '../evidence/associations';
import { rememberReference,returnPosition,restoreReference } from '../investigation/return-focus';
import { executionSchemas,executionCases,lanes,relationKinds,eventIssue,executionIssue,locator,type Trace,type Event,type Execution } from './schema';
import { useExecutionReader,useTrace,useExecutionPage } from './session';
import { ControlsPresentation } from './Controls';
import { FanoutHierarchy,partiality } from './Fanout';
const views=[{id:'events',label:'Events'},{id:'fanout',label:'Fanout'}],tabs=[{id:'details',label:'Details'},{id:'controls',label:'Controls'},{id:'provenance',label:'Provenance'}];
function usePhone(){const [phone,setPhone]=useState(()=>matchMedia('(max-width: 1023px)').matches);useEffect(()=>{const m=matchMedia('(max-width: 1023px)'),change=()=>setPhone(m.matches);m.addEventListener('change',change);return()=>m.removeEventListener('change',change);},[]);return phone;}
function Stale({error}:{error:unknown}){return error?<p role="status">STALE / DISCONNECTED — displaying valid previous projection.</p>:null;}
export default function Recorder(){
 const {params,update}=useControls(),name=params.get('execution_case')??'story',source=params.get('execution_trace')??'',view=params.get('execution_view')??'events',tab=params.get('execution_tab')??'details';
 const invalid=historicalRequested(params)||!executionCases.includes(name as typeof executionCases[number])||!views.some(v=>v.id===view)||!tabs.some(t=>t.id===tab)||['execution_trace','execution_selected','execution_filter','execution_invocation','execution_run','execution_work','execution_locator'].some(k=>params.has(k)&&!id.safeParse(params.get(k)).success)||(params.has('execution_run')&&!params.has('execution_invocation'))||(params.has('execution_display')&&!['lanes','table','hierarchy'].includes(params.get('execution_display')!))||(params.has('execution_kind')&&!['events','executions'].includes(params.get('execution_kind')!))||(params.has('execution_pane')&&!['results','detail'].includes(params.get('execution_pane')!))||(params.has('packet_tab')&&!packetTabs.some(t=>t.id===params.get('packet_tab')));
 useEffect(()=>{document.title='Recorded execution · AEW';},[]);
 return <><h1>Recorded execution</h1><p className="preview-note">Execution preview · 0.1.0 PROVISIONAL · Fictional recorded investigation. Frontend fixture acceptance is not backend adoption.</p><p className="scope-note">Presentation-fixture events do not define the T3 outbox contract. No historical state or causal conclusion is reconstructed.</p><div className="filter-bar"><Link to="/runs">Return to Runs</Link><CopyDashboardLink/><label>Execution scenario<select value={name} onChange={e=>update({...Object.fromEntries([...params.keys()].filter(k=>k.startsWith('execution_')).map(k=>[k,null])),execution_case:e.target.value})}>{executionCases.map(c=><option key={c}>{c}</option>)}</select></label></div>
 {invalid?<p role="alert">Unsupported execution presentation or historical link. No execution preview reads sent.</p>:<RecorderBody key={`${name}:${source}`} name={name} sourceId={source}/>}</>;
}
function RecorderBody({name,sourceId}:{name:string;sourceId:string}){
 const {params,update}=useControls(),inspector=params.get('execution_locator'),query=useTrace(name,sourceId,!inspector),t=query.data?.value.data;
 if(inspector)return <PacketHost name={name} sourceId={sourceId} locatorId={inspector}/>;
 if(!sourceId)return <TraceChooser name={name}/>;
 return <>{query.error&&<ErrorState error={query.error} retry={()=>void query.refetch()}/>} {t?<><div className="filter-bar"><p><code>{t.id}</code> · fixed <code>{t.snapshot_id}</code> · Captured UTC {t.captured_at}</p><button data-change-trace onClick={()=>update({execution_trace:null,execution_selected:null,execution_cursor:null,execution_locator:null})}>Change trace</button><button onClick={()=>void query.refetch()}>Refresh fixed trace</button></div><Stale error={query.error}/><Workspace trace={t} name={name} reader={query.reader}/></>:!query.error&&<p role="status">Loading fixed trace…</p>}</>;
}
function TraceChooser({name}:{name:string}){
 const {params,update}=useControls(),{reader,ready}=useExecutionReader('chooser',name),p=new URLSearchParams({case:name,limit:'50'});
 for(const [key,api] of [['execution_work','work'],['execution_invocation','invocation_id'],['execution_run','run_id'],['execution_trace_cursor','cursor']]){const v=params.get(key);if(v)p.set(api,v);}
 const q=useExecutionPage('/traces?'+p,executionSchemas.TraceListResponse,reader,ready);
 return <section><h2 tabIndex={-1}>Choose a fixed trace</h2><p>Choose explicitly; multiple matches are not ranked by age or outcome.</p><div className="filter-bar">{[['execution_work','Work ID'],['execution_invocation','Invocation ID'],['execution_run','Harness run ID']].map(([key,label])=><label key={key}>{label}<input value={params.get(key)??''} onChange={e=>update({[key]:e.target.value,execution_trace_cursor:null})}/></label>)}</div>{q.error&&<ErrorState error={q.error} retry={()=>void q.refetch()}/>}{q.data?<><div className="table-scroll"><table className="execution-table"><thead><tr><th>Trace</th><th>Snapshot</th><th>Work / root invocation / run</th><th>Captured UTC</th></tr></thead><tbody>{q.data.value.data.items.map(t=><tr key={t.id}><td data-label="Trace"><button onClick={()=>update({execution_trace:t.id,execution_selected:null,execution_cursor:null})}>Select {t.id}</button></td><td data-label="Snapshot">{t.snapshot_id}</td><td data-label="Work / root invocation / run">{t.work.id} · {t.invocation_id} · {t.run_id??'Invocation-level'}</td><td data-label="Captured UTC">{t.captured_at}</td></tr>)}</tbody></table></div>{!q.data.value.data.items.length&&<p>No recorded traces supplied for these filters.</p>}<Pager next={q.data.value.data.next_cursor} cursorKey="execution_trace_cursor" resetKey={`${name}:${p.get('work')}:${p.get('invocation_id')}:${p.get('run_id')}`}/><Stale error={q.error}/></>:!q.error&&<p role="status">Loading traces…</p>}</section>;
}
type Reader=ReturnType<typeof useExecutionReader>['reader'];
function Workspace({trace:t,name,reader}:{trace:Trace;name:string;reader:Reader}){
 const {params,update}=useControls(),phone=usePhone(),selected=params.get('execution_selected')??'',kind=params.get('execution_kind')??'events',view=params.get('execution_view')??'events',pane=params.get('execution_pane')??(selected?'detail':'results');
 const heading=useRef<HTMLHeadingElement>(null),origin=useRef<string|null>(null),[focusSelection,setFocusSelection]=useState(true),location=useLocation();
 const resultsVisible=!phone||!selected||pane==='results',detailVisible=!!selected&&(!phone||pane==='detail');
 const select=(id:string,k:string,explicit=false)=>{origin.current=id;setFocusSelection(phone||explicit);update({execution_selected:id,execution_kind:k,execution_pane:phone?'detail':null});};
 const close=()=>{update({execution_selected:null,execution_kind:null,execution_pane:'results'});requestAnimationFrame(()=>{const element=[...document.querySelectorAll<HTMLElement>('[data-execution-pick]')].find(e=>e.dataset.executionPick===(origin.current??selected));focusBelowHeader(element??heading.current);});};
 useLayoutEffect(()=>{const position=returnPosition(location.state);if(position&&resultsVisible){const link=[...document.querySelectorAll<HTMLElement>('[data-execution-locator]')].find(e=>e.dataset.executionLocator===position.reference);if(link)restoreReference(position,link);}},[location,resultsVisible]);
 return <><h2 ref={heading} tabIndex={-1}>Recorded investigation</h2><p role="status">Selected: <code>{selected||'None'}</code></p>{selected&&<button onClick={close}>Close detail</button>}{phone&&selected&&<div className="workspace-switch" role="group" aria-label="Execution pane"><button aria-pressed={pane==='results'} onClick={()=>update({execution_pane:'results'})}>Results</button><button aria-pressed={pane==='detail'} onClick={()=>{setFocusSelection(true);update({execution_pane:'detail'});}}>Detail · {selected}</button></div>}
 <div className={selected?'investigation-panes has-selection':'investigation-panes'}><section className="investigation-results" hidden={!resultsVisible} aria-label="Recorded results">{resultsVisible&&<><InvestigationTabs prefix="execution-view" label="Recorded results view" tabs={views} active={view} select={id=>update({execution_view:id,execution_cursor:null,execution_display:null})}/><div role="tabpanel" id={`execution-view-panel-${view}`} aria-labelledby={`execution-view-tab-${view}`}>{view==='events'?<EventResults trace={t} name={name} reader={reader} select={id=>select(id,'events')}/>:<ExecutionResults trace={t} name={name} reader={reader} select={id=>select(id,'executions')}/>}</div></>}</section>
 {selected&&<section hidden={!detailVisible} className="investigation-detail" aria-label="Recorded detail">{detailVisible&&<Selection key={`${kind}:${selected}`} trace={t} name={name} reader={reader} selected={selected} kind={kind} focus={focusSelection&&!returnPosition(location.state)} select={(id,k)=>select(id,k,true)}/>}</section>}</div></>;
}
function EventResults({trace:t,name,reader,select}:{trace:Trace;name:string;reader:Reader;select:(id:string)=>void}){
 const {params,update}=useControls(),lane=params.get('execution_lane')??'',execution=params.get('execution_filter')??'',display=params.get('execution_display')??'lanes',p=new URLSearchParams({case:name,limit:'50',...(lane?{lane}:{}),...(execution?{execution_id:execution}:{}),...(params.get('execution_cursor')?{cursor:params.get('execution_cursor')!}:{})});
 const schema=useMemo(()=>executionSchemas.EventListResponse.superRefine(({data:v},c)=>{if(v.items.some(e=>eventIssue(e,t)))c.addIssue({code:'custom',message:'Event page binding mismatch'});}),[t]);
 const q=useExecutionPage(`/traces/${t.id}/events?`+p,schema,reader),selected=params.get('execution_selected');
 return <><div className="filter-bar"><label>Lane<select value={lane} onChange={e=>update({execution_lane:e.target.value,execution_cursor:null})}><option value="">All</option>{[...new Set([...lanes,...t.coverage.map(c=>c.lane)])].map(l=><option key={l}>{l}</option>)}</select></label><label>Execution ID<input value={execution} onChange={e=>update({execution_filter:e.target.value,execution_cursor:null})}/></label><button aria-pressed={display==='lanes'} onClick={()=>update({execution_display:'lanes'})}>Lanes</button><button aria-pressed={display==='table'} onClick={()=>update({execution_display:'table'})}>Table</button></div>
 <details><summary>Supplied lane coverage, recording gaps and retention</summary>{t.coverage.map(c=><section key={c.lane}><h3><SemanticValue value={c.lane} known={lanes}/></h3><p>{c.complete?'Complete supplied lane coverage':'Incomplete supplied lane coverage'} · Retention <SemanticValue value={c.retention} known={['FIXTURE_ONLY','UNAVAILABLE']}/></p><p>{c.explanation??'No coverage explanation supplied.'}</p>{c.gaps.map(g=><p key={g.id}>{g.id}: {g.explanation} · Source {g.source.id}</p>)}</section>)}<p>Ordinal discontinuities alone do not establish missing events. Only explicitly supplied gaps are shown.</p></details>
 {q.error&&<ErrorState error={q.error} retry={()=>void q.refetch()}/>} {q.data?<><button onClick={()=>void q.refetch()}>Refresh event page</button>{selected&&params.get('execution_kind')!=='executions'&&!q.data.value.data.items.some(e=>e.id===selected)&&<p>Selected event is outside the current results; its supplied detail is resolved separately.</p>}
 {display==='table'?<div className="table-scroll"><table className="execution-table"><thead><tr><th>Supplied order</th><th>Event / summary</th><th>Lane</th><th>Execution</th><th>Source UTC</th></tr></thead><tbody>{q.data.value.data.items.map(e=><tr key={e.id}><td data-label="Supplied order">{e.ordinal??'Unordered'}</td><td data-label="Event / summary"><button data-execution-pick={e.id} aria-pressed={selected===e.id} onClick={()=>select(e.id)}>{e.id}</button><p>{e.summary}</p></td><td data-label="Lane"><SemanticValue value={e.lane} known={lanes}/></td><td data-label="Execution">{e.execution_id}</td><td data-label="Source UTC">{e.source_at??'Not supplied'}</td></tr>)}</tbody></table></div>:<ol className="execution-lanes">{q.data.value.data.items.map(e=><li key={e.id} className="execution-event"><span className="execution-order">{e.ordinal??'Unordered'}</span><span className="execution-lane"><SemanticValue value={e.lane} known={lanes}/></span><div><button data-execution-pick={e.id} aria-pressed={selected===e.id} onClick={()=>select(e.id)}>{e.id}</button><p>{e.summary}</p><small>{e.execution_id} · Source UTC {e.source_at??'Not supplied'}</small></div></li>)}</ol>}
 {!q.data.value.data.items.length&&<p>No recorded events supplied for these filters.</p>}<Pager next={q.data.value.data.next_cursor} cursorKey="execution_cursor" resetKey={`${name}:${t.id}:${lane}:${execution}`}/><Stale error={q.error}/></>:!q.error&&<p role="status">Loading recorded events…</p>}</>;
}
function ExecutionResults({trace:t,name,reader,select}:{trace:Trace;name:string;reader:Reader;select:(id:string)=>void}){
 const {params,update}=useControls(),display=params.get('execution_display')??'hierarchy';
 const schema=useMemo(()=>executionSchemas.ExecutionListResponse.superRefine(({data:v},c)=>{if(v.items.some(e=>executionIssue(e,t)))c.addIssue({code:'custom',message:'Execution page binding mismatch'});}),[t]);
 const q=useExecutionPage(`/traces/${t.id}/executions?`+new URLSearchParams({case:name,limit:'50',...(params.get('execution_cursor')?{cursor:params.get('execution_cursor')!}:{})}),schema,reader,display==='table');
 return <><div className="filter-bar"><button aria-pressed={display==='hierarchy'} onClick={()=>update({execution_display:'hierarchy'})}>Hierarchy</button><button aria-pressed={display==='table'} onClick={()=>update({execution_display:'table'})}>Table</button></div><p>{partiality}</p>{!t.executions_complete&&<p>Execution coverage is incomplete. Unknown or unregistered references do not establish absence of registration elsewhere.</p>}{display==='hierarchy'?<FanoutHierarchy key={`${t.id}:${name}`} trace={t} name={name} reader={reader} select={select}/>:<>{q.error&&<ErrorState error={q.error} retry={()=>void q.refetch()}/>} {q.data?<><div className="table-scroll"><table className="execution-table"><thead><tr><th>Execution</th><th>Class / registration</th><th>Invocation / run</th><th>Supplied relationships</th></tr></thead><tbody>{q.data.value.data.items.map(e=><tr key={e.id}><td data-label="Execution"><button data-execution-pick={e.id} onClick={()=>select(e.id)}>{e.id}</button></td><td data-label="Class / registration"><SemanticValue value={e.execution_class} known={['invocation','helper']}/> · <SemanticValue value={e.registration_state} known={['registered','unregistered','unknown']}/></td><td data-label="Invocation / run">{e.invocation?.id??'Not supplied'} · {e.run_id??'Not supplied'}</td><td data-label="Supplied relationships">{e.relations.map(r=><p key={r.id}><SemanticValue value={r.relation_kind} known={relationKinds}/> → {r.to.id} · Source {r.source.id}</p>)}{!e.relations_complete&&<p>Incomplete supplied relations.</p>}</td></tr>)}</tbody></table></div><Pager next={q.data.value.data.next_cursor} cursorKey="execution_cursor" resetKey={`${t.id}:${name}:executions`}/><Stale error={q.error}/></>:!q.error&&<p role="status">Loading execution table…</p>}</>}</>;
}
function Selection({trace:t,name,reader,selected,kind,focus,select}:{trace:Trace;name:string;reader:Reader;selected:string;kind:string;focus:boolean;select:(id:string,k:string)=>void}){
 const {params,update}=useControls(),tab=params.get('execution_tab')??'details',heading=useRef<HTMLHeadingElement>(null),focused=useRef(false);
 const eventSchema=useMemo(()=>executionSchemas.EventResponse.superRefine(({data:e},c)=>{if(e.id!==selected||eventIssue(e,t))c.addIssue({code:'custom',message:'Selected event binding mismatch'});}),[selected,t]);
 const eventQuery=useExecutionPage(`/traces/${t.id}/events/${selected}?case=${name}`,eventSchema,reader,kind==='events'),event=kind==='events'?eventQuery.data?.value.data:undefined;
 const executionId=kind==='executions'?selected:event?.execution_id??'';
 const execSchema=useMemo(()=>executionSchemas.ExecutionResponse.superRefine(({data:e},c)=>{const issue=executionIssue(e,t);if(e.id!==executionId||issue||(event&&(e.invocation?.id??null)!==event.invocation_id)||(event&&e.run_id!==event.run_id))c.addIssue({code:'custom',message:issue??'Event invocation/execution binding mismatch'});}),[executionId,t,event]);
 const execQuery=useExecutionPage(`/traces/${t.id}/executions/${executionId}?case=${name}`,execSchema,reader,!!executionId),execution=execQuery.data?.value.data;
 useEffect(()=>{if(focus&&!focused.current&&(event||execution)){focusBelowHeader(heading.current);focused.current=true;}},[focus,!!event,!!execution]);
 const error=eventQuery.error??execQuery.error;
 return <><h2 tabIndex={-1} ref={heading}>{selected}</h2>{error&&<ErrorState error={error} retry={()=>void(kind==='events'?eventQuery.refetch():execQuery.refetch())}/>} {!event&&!execution&&!error&&<p role="status">Resolving selected recorded identity…</p>}
 {(event||execution)&&<><p><code>{t.id}</code> · <code>{t.snapshot_id}</code> · <code>{executionId}</code></p><InvestigationTabs prefix="execution-detail" label="Recorded detail sections" tabs={tabs} active={tab} select={id=>update({execution_tab:id,execution_receipt_cursor:null})}/><div role="tabpanel" id={`execution-detail-panel-${tab}`} aria-labelledby={`execution-detail-tab-${tab}`}>
 {tab==='details'&&<>{event&&<><p>Supplied ordinal: {event.ordinal??'Unordered'} · Source UTC {event.source_at??'Not supplied'} · Observation UTC {event.observed_at??'Not supplied'}</p><p><SemanticValue value={event.lane} known={lanes}/> · <SemanticValue value={event.kind} known={['recorded_activity','tool_reference','evidence_publication','preparation','delivery','citation','reported_transition','review_reference']}/></p><SafeContent format="plain" text={event.summary}/><Reasons values={event.reasons}/><div className="filter-bar">{event.previous_id&&<button onClick={()=>select(event.previous_id!,'events')}>Previous recorded event</button>}{event.next_id&&<button onClick={()=>select(event.next_id!,'events')}>Next recorded event</button>}</div><CrossReferences event={event} trace={t} name={name}/></>}{execution&&<CapturedExecution value={execution}/>}</>}
 {tab==='controls'&&execution&&<ControlsPresentation key={executionId} trace={t} executionId={executionId} name={name} reader={reader}/>}
 {tab==='provenance'&&<><p>{partiality}</p>{execution&&<><h3>Supplied typed relations and source attribution</h3>{execution.relations.map(r=><section className="panel execution-relation" key={r.id}><SemanticValue value={r.relation_kind} known={relationKinds}/><p>{r.from.id} → {r.to.id} · Source {r.source.id}</p><ContextReferences values={r.provenance}/><details><summary>Supplied relation metadata</summary><JsonContent value={r}/></details></section>)}{!execution.relations_complete&&<p>Incomplete supplied relationship list.</p>}</>}<h3>Canonical references</h3><ContextReferences values={t.canonical_references}/><p>Canonical decisions remain references to their authoritative records.</p><details><summary>Trace coverage and response metadata</summary><JsonContent value={t.coverage}/>{eventQuery.data&&<SourceStrip source={eventQuery.data} readSnapshot={t.snapshot_id} failed={!!error}/>} {execQuery.data&&<SourceStrip source={execQuery.data} readSnapshot={t.snapshot_id} failed={!!error}/>}</details></>}
 </div><Stale error={error}/></>}</>;
}
function CapturedExecution({value:e}:{value:Execution}){
 return <section><h3>Captured execution</h3><p><SemanticValue value={e.execution_class} known={['invocation','helper']}/> · <SemanticValue value={e.registration_state} known={['registered','unregistered','unknown']}/></p>{e.invocation?<><p>Invocation {e.invocation.id} · Role <SemanticValue value={e.invocation.role} known={invocationRoles}/> · Status at source capture <SemanticValue value={e.invocation.status} known={invocationStatuses}/></p><p>This captured status is not status at the selected event.</p><SafeContent {...e.invocation.summary}/><h4>Accepted harness-run records</h4>{e.invocation.runs.map(r=><p key={r.id}>{r.id} · {r.harness} · <SemanticValue value={r.status} known={harnessStatuses}/> · {r.authority} · Launched UTC {r.launched_at}</p>)}</>:<p>No invocation/run record supplied. Process references remain terminal; no process inspector.</p>}</section>;
}
function PacketReference({id,packet,open}:{id:string;packet:string;open:()=>void}){
 const location=useLocation(),element=useRef<HTMLButtonElement>(null),restored=useRef(false);
 useLayoutEffect(()=>{const position=returnPosition(location.state);if(!restored.current&&position?.reference===id&&element.current?.getClientRects().length){restoreReference(position,element.current);restored.current=true;}});
 return <button ref={element} data-execution-locator={id} onClick={()=>{rememberReference(id);open();}}>Inspect packet {packet}</button>;
}
function CrossReferences({event,trace,name}:{event:Event;trace:Trace;name:string}){
 const {update}=useControls();
 return <><ContextReferences values={event.references.filter(r=>r.kind!=='evidence_reference')}/>{event.locator_ids.map(lid=>{const mapping=manifest.mappings.find(m=>m.id===lid&&m.origin.record_id===event.id&&m.origin.case===name&&m.origin.source_id===trace.id&&m.origin.snapshot_id===trace.snapshot_id&&m.origin.project_id===trace.project_id);if(!mapping||!locator.safeParse(mapping).success)return <p key={lid}>Reference {lid} unavailable: no exact mapping supplied.</p>;const a=inspectionAssociations.find(a=>a.reference_id===mapping.target.reference_id);return mapping.target.contract==='evidence-preview'&&a?<p key={lid}><EvidenceReference origin={a.origin}>Inspect evidence {a.origin.evidence_id}</EvidenceReference></p>:<p key={lid}><PacketReference id={lid} packet={mapping.target.record_id} open={()=>update({execution_locator:lid,packet_tab:null,packet_cursor:null})}/></p>;})}<p>Prepared context, delivery acknowledgment, output citation and evaluated benefit remain distinct. No attention, influence or benefit is inferred.</p></>;
}
function PacketHost({name,sourceId,locatorId}:{name:string;sourceId:string;locatorId:string}){
 const {params,update}=useControls(),navigate=useNavigate(),originIndex=useRef(window.history.state?.idx>0?window.history.state.idx-1:null),selected=params.get('execution_selected'),mapping=manifest.mappings.find(m=>m.id===locatorId&&m.origin.case===name&&m.origin.source_id===sourceId&&m.origin.record_id===selected&&m.target.contract==='investigation-preview');
 const project=useDashboard().project.data?.value.project_id;
 const valid=!!mapping&&locator.safeParse(mapping).success&&!!project&&mapping.origin.project_id===project;
 const query=useComparisonSource('execution-packet',mapping?.target.case??'story',valid?mapping!.target.source_id:'',false,true),s=query.data?.value.data;
 const mismatch=s&&mapping&&(s.snapshot_id!==mapping.target.snapshot_id||s.invocation.id!==mapping.target.invocation_id||s.visibility_scope!==mapping.target.visibility_scope||!s.packets.some(p=>p.id===mapping.target.record_id&&p.run_id===mapping.target.run_id));
 if(!valid||mismatch)return <p role="alert">Cross-preview locator binding mismatch or unavailable mapping. No packet read sent.</p>;
 return <PacketInspector query={query} packetId={mapping!.target.record_id} name={mapping!.target.case} backLabel="Back to recorded execution" back={()=>{const now=window.history.state?.idx;if(originIndex.current!==null&&now>originIndex.current)navigate(originIndex.current-now);else update({execution_locator:null});}}/>;
}
