import { describe,it,expect } from 'vitest';
import { createHash } from 'node:crypto';
import { EvidenceProjector,evidenceBase } from '../src/api/preview/evidence/projector';
import { evidenceSchemas,excerptIssue,sourceIssue } from '../src/api/preview/evidence/schema';
import { evidenceFixture,referenceAssociations } from '../src/api/preview/evidence/fixtures';
import { sha256 } from '../src/api/preview/evidence/digest';
import { visibleSource,citation } from '../src/api/preview/evidence/model';
import { ReadTransport } from '../src/api/transport';
const url=(route:string)=>new URL(evidenceBase+route,'http://demo.test');
describe('Evidence identities and bounded source rendering',()=>{
  it('matches native SHA-256 including padding boundaries and Unicode',()=>{for(const text of ['', 'abc', 'a'.repeat(55),'a'.repeat(56),'a'.repeat(64),'☃😀\r\n'.repeat(3000)])expect(sha256(text)).toBe(createHash('sha256').update(text).digest('hex'));});
  it('keeps canonical Evidence separate from its originating associations',()=>{const matches=referenceAssociations.filter(a=>a.origin.evidence_id==='CLANGD-E875');expect(new Set(matches.map(a=>a.reference_id)).size).toBe(matches.length);const p=new EvidenceProjector();for(const a of matches){const v=evidenceSchemas.ReferenceResponse.parse(p.read(url(`/references/${a.reference_id}`)).body);expect(v.data.origin).toEqual(a.origin);expect(v.data.source_ids).toEqual(a.source_ids);}expect(p.read(url('/references/CLANGD-E875')).status).toBe(404);});
  it('validates story source payloads through the unchanged accepted parser',()=>{for(const s of evidenceFixture().sources){expect(sourceIssue(s)).toBeUndefined();expect(evidenceSchemas.EvidenceSourceResponse.safeParse({schema_version:'0.1.0',project_id:'aew-demo',control_revision:'42',generated_at:'2026-10-03T12:00:00Z',data:s}).success).toBe(true);}});
  it('never leaks candidate identity on refusal and distinguishes historical unavailable',()=>{const p=new EvidenceProjector();expect(p.read(url('/sources?case=denied'))).toEqual({status:403});expect(p.read(url('/sources/ES-Removal?case=historical-unavailable'))).toEqual({status:410});expect(p.read(url('/sources/ES-Removal?case=malformed')).body).not.toBeUndefined();expect(evidenceSchemas.EvidenceSourceResponse.safeParse(p.read(url('/sources/ES-Removal?case=malformed')).body).success).toBe(false);});
  it('pages at UTF-8 boundaries and does not accept another artifact cursor',()=>{const p=new EvidenceProjector(),path='/sources/ES-Removal/artifacts/ART-000/excerpt?case=large&artifact_revision=1';const first=evidenceSchemas.ExcerptResponse.parse(p.read(url(path)).body).data;expect(first.byte_end).toBeLessThanOrEqual(16384);expect(first.next_cursor).not.toBeNull();const second=evidenceSchemas.ExcerptResponse.parse(p.read(url(path+'&cursor='+encodeURIComponent(first.next_cursor!))).body).data;expect(second.byte_start).toBe(first.byte_end);expect(second.text).not.toContain('\uFFFD');expect(p.read(url(path.replace('ART-000','ART-001')+'&cursor='+encodeURIComponent(first.next_cursor!))).status).toBe(400);});
  it('rejects integrity/range and exact artifact binding before caching',async()=>{const p=new EvidenceProjector(),f=evidenceFixture(),s=f.sources[0],a=f.artifacts[0];const v=evidenceSchemas.ExcerptResponse.parse(p.read(url('/sources/ES-Removal/artifacts/ART-Removal/excerpt?artifact_revision=1')).body);expect(excerptIssue(v.data,s,a,null)).toBeUndefined();expect(excerptIssue({...v.data,artifact_id:'OTHER'},s,a,null)).toContain('mismatch');expect(evidenceSchemas.ExcerptResponse.safeParse({...v,data:{...v.data,byte_end:999}}).success).toBe(false);let calls=0;const t=new ReadTransport(async()=>{calls++;return new Response(JSON.stringify({...v,data:{...v.data,sha256:'0'.repeat(64)}}));},undefined,undefined,{base:evidenceBase,routes:/^\/sources/});t.context.bind('aew-demo');await expect(t.get('/sources/x',evidenceSchemas.ExcerptResponse)).rejects.toThrow();await expect(t.get('/sources/x',evidenceSchemas.ExcerptResponse)).rejects.toThrow();expect(calls).toBe(2);});
  it('neutralizes bidi, isolates, ANSI and invisible controls without changing digest',()=>{const raw='x\u202Ey\u202C\u2066z\u2069\u001b[31m\u200B\uFEFF';expect(visibleSource(raw)).toBe('x⟦U+202E⟧y⟦U+202C⟧⟦U+2066⟧z⟦U+2069⟧⟦U+001B⟧[31m⟦U+200B⟧⟦U+FEFF⟧');expect(sha256(raw)).not.toBe(sha256(visibleSource(raw)));expect(visibleSource('a\nb\tc')).toBe('a\nb\tc');});
  it('pins citation to artifact identity and original byte range without its body',()=>{const p=new EvidenceProjector(),f=evidenceFixture(),x=evidenceSchemas.ExcerptResponse.parse(p.read(url('/sources/ES-Removal/artifacts/ART-Removal/excerpt?artifact_revision=1')).body).data;const text=citation(f.sources[0],f.artifacts[0],x,'http://demo.test/evidence/inspect?evidence_artifact=ART-Removal','REF-J05-CLANGD-E871');expect(text).toContain('Artifact: ART-Removal');expect(text).toContain('Artifact revision: 1');expect(text).toContain('Bytes: [0,');expect(text).not.toContain(x.text);expect(text).toContain('supplied; not verified');});
  it('bounds and binds collection cursors to filters and project',()=>{const p=new EvidenceProjector(),first=evidenceSchemas.ArtifactListResponse.parse(p.read(url('/sources/ES-Removal/artifacts?case=large')).body);expect(first.data.items).toHaveLength(50);const cursor=encodeURIComponent(first.data.next_cursor!);expect(p.read(url('/sources/ES-Removal/artifacts?case=large&artifact_id=ART-001&cursor='+cursor)).status).toBe(400);expect(p.read(url('/sources/ES-Removal/artifacts?case=large&cursor='+cursor),'other-project').status).toBe(400);});
});

