import { ContextReferences as References } from '../investigation/ContextReferences';
import { useEffect,useMemo,useRef,useState } from 'react';
import { Link,useLocation,useNavigate } from 'react-router-dom';
import { useProjection } from '../../../client/queries';
import { useControls,ErrorState } from '../investigation/ui';
import { InvestigationTabs,focusBelowHeader } from '../../../components/InvestigationTabs';
import { Pager,Reasons } from '../../../components/ProjectionViews';
import { SourceStrip } from '../../../components/Investigation';
import { SafeContent,JsonContent } from '../../../components/Content';
import { SemanticValue } from '../../../components/States';
import { evidenceKinds,evidenceResults,evidenceCurrentness } from '../../vocabulary';
import { dashboardCopyLink,historicalRequested } from '../../navigation';
import { id } from '../../schema';
import { evidenceSchemas,evidenceCases,supportedMedia,excerptIssue,type Artifact,type Association,type EvidenceSource } from './schema';
import { sameOrigin } from './fixtures';
import { inspectionAssociations,inspectionTarget } from './associations';
import { useEvidenceReader,useEvidenceSource,useBoundedExcerpt,type SourceQuery } from './session';
import { citation,visibleSource } from './model';
const tabs=[{id:'record',label:'Record'},{id:'artifacts',label:'Artifacts'},{id:'provenance',label:'Provenance'}];
function Note({error}:{error:unknown}){return error?<p role="status">STALE / DISCONNECTED — displaying valid prior data.</p>:null;}
export default function EvidenceReader(){
  const {params,update}=useControls(),name=params.get('evidence_case')??'story',tab=params.get('evidence_tab')??'record',source=params.get('evidence_source')??'',reference=params.get('evidence_reference')??'';
  const navigate=useNavigate(),location=useLocation(),[copied,setCopied]=useState('');
  const originIndex=useRef((location.state as {evidenceReturn?:boolean}|null)?.evidenceReturn===true&&Number.isInteger(window.history.state?.idx)?window.history.state.idx-1:null);
  const invalid=(params.has('evidence_pane')&&!['list','detail'].includes(params.get('evidence_pane')!))||historicalRequested(params)||!evidenceCases.includes(name as typeof evidenceCases[number])||!tabs.some(t=>t.id===tab)||['evidence_source','evidence_reference','evidence_artifact','evidence_revision','evidence_filter','evidence_work'].some(k=>params.has(k)&&!id.safeParse(params.get(k)).success)||params.has('evidence_artifact')!==params.has('evidence_revision');
  useEffect(()=>{document.title='Evidence inspection · AEW';},[]);
  return <><div className="page-heading"><div><h1>Evidence inspection</h1><p className="preview-note">Evidence inspection preview · 0.1.0 PROVISIONAL · Fictional projections. Frontend acceptance is not backend adoption.</p></div></div>
    <div className="filter-bar"><button onClick={()=>{const now=window.history.state?.idx;if(originIndex.current!==null&&Number.isInteger(now)&&now>originIndex.current)navigate(originIndex.current-now);else navigate('/evidence');}}>Back to originating investigation</button><Link to="/evidence">Evidence records</Link><button onClick={()=>void navigator.clipboard.writeText(dashboardCopyLink(location.pathname,location.search,window.location.origin)).then(()=>setCopied('Dashboard link copied.')).catch(()=>setCopied('Copy unavailable; use the address bar.'))}>Copy dashboard link</button></div><p role="status">{copied}</p>
    <label className="journal-case">Evidence scenario<select aria-label="Evidence scenario" value={name} onChange={e=>update({...Object.fromEntries([...params.keys()].filter(k=>k.startsWith('evidence_')).map(k=>[k,null])),evidence_case:e.target.value})}>{evidenceCases.map(c=><option key={c}>{c}</option>)}</select></label>
    {invalid?<p role="alert">Unsupported evidence presentation or historical link. No evidence preview read was sent.</p>:<ReaderBody key={`${name}:${reference}`} name={name} sourceId={source} referenceId={reference} tab={tab}/>}</>;
}
function ReaderBody({name,sourceId,referenceId,tab}:{name:string;sourceId:string;referenceId:string;tab:string}){
  const expected=inspectionAssociations.find(a=>a.reference_id===referenceId),{reader,ready}=useEvidenceReader(`reference:${referenceId}:${JSON.stringify(expected?.origin??null)}`,name),{update}=useControls();
  const schema=useMemo(()=>evidenceSchemas.ReferenceResponse.superRefine(({data:a},ctx)=>{if(!expected||a.reference_id!==referenceId||!sameOrigin(a.origin,expected.origin)||a.source_ids.some(id=>!expected.source_ids.includes(id)))ctx.addIssue({code:'custom',message:'Reference association/origin binding mismatch'});}),[expected,referenceId]);
  const resolution=useProjection(`/references/${encodeURIComponent(referenceId)}?case=${encodeURIComponent(name)}`,schema,'history',ready&&!!referenceId&&!!expected,true,reader,false);
  if(referenceId&&!expected)return <p role="alert">No inspection mapping supplied for this reference association.</p>;
  if(referenceId&&!resolution.data)return resolution.error?<ErrorState error={resolution.error} retry={()=>void resolution.refetch()}/>:<p role="status">Resolving supplied reference association…</p>;
  const association=resolution.data?.value.data;
  if(sourceId&&association&&!association.source_ids.includes(sourceId))return <p role="alert">Selected source is not supplied for this association. No source read was sent.</p>;
  return <>{resolution.error&&<><ErrorState error={resolution.error} retry={()=>void resolution.refetch()}/><Note error={resolution.error}/></>}{association&&<details><summary>Reference association {association.reference_id}</summary><JsonContent value={association.origin}/>{!association.complete&&<p>Reference resolution is incomplete.</p>}</details>}
    {sourceId?<><button onClick={()=>update({evidence_source:null,evidence_artifact:null,evidence_revision:null,evidence_excerpt_cursor:null,evidence_artifact_cursor:null})}>Change evidence source</button><SelectedSource key={`${name}:${sourceId}`} name={name} sourceId={sourceId} association={association} tab={tab}/></>:<SourceChooser name={name} association={association}/>}</>;
}
function SourceChooser({name,association}:{name:string;association?:Association}){
  const {reader,ready}=useEvidenceReader(`chooser:${association?.reference_id??'all'}`,name),{params,update}=useControls();
  const p=new URLSearchParams({case:name,limit:'50'});for(const [url,key] of [['evidence_id','evidence_filter'],['work','evidence_work'],['cursor','evidence_source_cursor']] as const){const v=params.get(key);if(v)p.set(url,v);}if(association)p.set('reference_id',association.reference_id);
  const schema=useMemo(()=>evidenceSchemas.EvidenceSourceListResponse.superRefine(({data:v},ctx)=>{if(association&&v.items.some(s=>!association.source_ids.includes(s.id)||s.evidence_id!==association.origin.evidence_id))ctx.addIssue({code:'custom',message:'Resolved source identity mismatch'});}),[association]);
  const query=useProjection('/sources?'+p,schema,'history',ready,true,reader,false);
  return <section><h2>Choose an explicit evidence source</h2>{!association&&<div className="filter-bar">{[['evidence_filter','Evidence ID'],['evidence_work','Work ID']].map(([key,label])=><label key={key}>{label}<input value={params.get(key)??''} onChange={e=>update({[key]:e.target.value,evidence_source_cursor:null})}/></label>)}</div>}
    {query.error&&<ErrorState error={query.error} retry={()=>void query.refetch()}/>}{query.data?<><Note error={query.error}/><div className="table-scroll"><table className="evidence-table"><thead><tr><th>Source</th><th>Evidence</th><th>Work</th><th>Snapshot / revision</th><th>Captured UTC</th></tr></thead><tbody>{query.data.value.data.items.map(s=><tr key={s.id}><td data-label="Source"><button onClick={()=>update({evidence_source:s.id,evidence_tab:'record'})}>{s.id}</button></td><td data-label="Evidence">{s.evidence_id}</td><td data-label="Work">{s.work.id}</td><td data-label="Snapshot / revision">{s.snapshot_id} · {s.source_revision??'Not supplied'}</td><td data-label="Captured UTC">{s.captured_at}</td></tr>)}</tbody></table></div>{!query.data.value.data.items.length&&<p>No evidence sources supplied for these filters.</p>}<Pager next={query.data.value.data.next_cursor} cursorKey="evidence_source_cursor" resetKey={`${name}:${association?.reference_id}:${params.get('evidence_filter')}:${params.get('evidence_work')}`}/></>:!query.error&&<p role="status">Loading evidence sources…</p>}</section>;
}
function SelectedSource({name,sourceId,association,tab}:{name:string;sourceId:string;association?:Association;tab:string}){
  const target=association&&inspectionTarget(association.reference_id);
  const query=useEvidenceSource(name,sourceId,target),s=query.data?.value.data,{update}=useControls(),heading=useRef<HTMLHeadingElement>(null);
  useEffect(()=>{if(s)focusBelowHeader(heading.current);},[!!s]);
  if(target&&s&&(s.id!==target.source_id||s.snapshot_id!==target.snapshot_id||s.visibility_scope!==target.visibility_scope||s.evidence.bindings.producer?.invocation!==target.invocation_id||s.evidence.bindings.producer?.run!==target.run_id))return <p role="alert">Cross-preview Evidence source/snapshot/run binding mismatch.</p>;
  if(association&&s&&(s.evidence_id!==association.origin.evidence_id||!association.source_ids.includes(s.id)))return <p role="alert">Evidence source association mismatch.</p>;
  return <section><h2 ref={heading} tabIndex={-1}>{s?.evidence_id??sourceId}</h2>{query.error&&<ErrorState error={query.error} retry={()=>void query.refetch()}/>}{s?<><p><code>{s.id}</code> · <code>{s.snapshot_id}</code> · {s.source_revision??'Revision not supplied'} · captured UTC {s.captured_at}</p><Note error={query.error}/><button onClick={()=>void query.refetch()}>Refresh fixed source</button><InvestigationTabs prefix="evidence" label="Evidence reader sections" tabs={tabs} active={tab} select={id=>update({evidence_tab:id})}/><div id={`evidence-panel-${tab}`} role="tabpanel" aria-labelledby={`evidence-tab-${tab}`}>
    {tab==='record'&&<section className="panel"><p>Kind: <SemanticValue value={s.evidence.kind} known={evidenceKinds} /> · Reported result: <SemanticValue value={s.evidence.result} known={evidenceResults}/> · Currentness: <SemanticValue value={s.evidence.currentness} known={evidenceCurrentness}/></p><h3>Claim</h3><SafeContent {...s.evidence.claim}/><h3>Evidence body</h3><SafeContent {...s.evidence.body}/><h3>Findings</h3><Reasons values={s.evidence.findings}/><h3>Deviations</h3><Reasons values={s.evidence.deviations}/></section>}
    {tab==='artifacts'&&<Artifacts key={s.id} name={name} source={s} query={query} reference={association?.reference_id??null}/>}
    {tab==='provenance'&&<section className="panel"><h3>Bindings and producer</h3><JsonContent value={s.evidence.bindings}/><h3>Provenance references</h3><References values={s.evidence.provenance}/><h3>Canonical references</h3><References values={s.canonical_references}/><p>Canonical decisions remain references to their authoritative records. Included context and reported outcomes do not establish causal benefit.</p><details><summary>Response metadata</summary><SourceStrip source={query.data!} readSnapshot={s.snapshot_id} failed={!!query.error}/></details></section>}
    </div></>:!query.error&&<p role="status">Loading fixed evidence source…</p>}</section>;
}
function Artifacts({name,source:s,query:sourceQuery,reference}:{name:string;source:EvidenceSource;query:SourceQuery;reference:string|null}){
  const {params,update}=useControls(),aid=params.get('evidence_artifact')??'',revision=params.get('evidence_revision')??'',cursor=params.get('evidence_artifact_cursor'),pane=params.get('evidence_pane')??'list';
  const schema=useMemo(()=>evidenceSchemas.ArtifactListResponse.superRefine(({data:v},ctx)=>{if(v.items.some(a=>a.source_id!==s.id||a.evidence_id!==s.evidence_id||a.snapshot_id!==s.snapshot_id))ctx.addIssue({code:'custom',message:'Artifact source binding mismatch'});}),[s]);
  const route=`/sources/${s.id}/artifacts?`+new URLSearchParams({case:name,limit:'50',...(cursor?{cursor}: {})}),query=useProjection(route,schema,'history',true,true,sourceQuery.reader,false);
  const selectedSchema=useMemo(()=>schema.superRefine(({data:v},ctx)=>{if(v.items.length!==1||v.items[0].id!==aid||v.items[0].revision!==revision)ctx.addIssue({code:'custom',message:'Selected artifact identity/revision unavailable'});}),[schema,aid,revision]);
  const selected=useProjection(`/sources/${s.id}/artifacts?`+new URLSearchParams({case:name,artifact_id:aid,limit:'50'}),selectedSchema,'history',!!aid,true,sourceQuery.reader,false),a=selected.data?.value.data.items[0];
  const [narrow,setNarrow]=useState(window.matchMedia('(max-width: 1023px)').matches),list=useRef<HTMLElement>(null),focusSelection=useRef<string|null>(null);
  useEffect(()=>{const m=window.matchMedia('(max-width: 1023px)'),f=()=>setNarrow(m.matches);m.addEventListener('change',f);return()=>m.removeEventListener('change',f);},[]);
  const detailShown=!!aid&&(!narrow||pane==='detail');
  const sharedError=!!query.error&&!!selected.error&&query.error.message===selected.error.message;
  return <><p role="status">Selected artifact: {aid||'None'}{aid&&(selected.error?' · unavailable':a&&query.data&&!query.data.value.data.items.some(v=>v.id===aid)?' · outside the displayed page':'')}</p>{!s.artifacts_complete&&<p className="preview-note">Artifact associations are incomplete.</p>}
    {narrow&&aid&&<div className="filter-bar"><button aria-pressed={pane==='list'} onClick={()=>update({evidence_pane:'list'})}>List</button><button aria-pressed={pane==='detail'} onClick={()=>{focusSelection.current=aid+':'+revision;update({evidence_pane:'detail'});}}>Detail · {aid}</button></div>}
    {sharedError&&<ErrorState error={query.error} retry={()=>{void query.refetch();void selected.refetch();}}/>}<div className={`evidence-panes ${detailShown?'has-selection':''}`}><section ref={list} hidden={narrow&&pane==='detail'&&!!aid} tabIndex={-1}><h3>Supplied artifacts</h3>{query.error&&!sharedError&&<ErrorState error={query.error} retry={()=>void query.refetch()}/>}{query.data?<><Note error={query.error}/><div className="table-scroll"><table className="evidence-table"><thead><tr><th>Artifact</th><th>Revision</th><th>Media / availability</th></tr></thead><tbody>{query.data.value.data.items.map(v=><tr key={v.id}><td data-label="Artifact"><button data-artifact-id={v.id} onClick={()=>{focusSelection.current=v.id+':'+v.revision;update({evidence_artifact:v.id,evidence_revision:v.revision,evidence_excerpt_cursor:null,evidence_pane:narrow?'detail':'list'});}}>{v.id} · {v.display_name??'Name not supplied'}</button></td><td data-label="Revision">{v.revision}</td><td data-label="Media / availability">{v.media_type} · <SemanticValue value={v.availability} known={['AVAILABLE','UNAVAILABLE','DENIED']}/></td></tr>)}</tbody></table></div>{!query.data.value.data.items.length&&<p>No artifact associations supplied.</p>}<Pager next={query.data.value.data.next_cursor} cursorKey="evidence_artifact_cursor" resetKey={`${name}:${s.id}`}/></>:!query.error&&<p role="status">Loading artifact associations…</p>}</section>
    {aid&&<section hidden={!detailShown}>{selected.error&&!sharedError&&<ErrorState error={selected.error} retry={()=>void selected.refetch()}/>}{a&&detailShown&&<ArtifactDetail key={`${s.id}:${a.id}:${a.revision}`} name={name} source={s} artifact={a} query={sourceQuery} reference={reference} onOpen={element=>{if(focusSelection.current===a.id+':'+a.revision){focusSelection.current=null;focusBelowHeader(element);}}}/>}<button onClick={()=>{update({evidence_artifact:null,evidence_revision:null,evidence_excerpt_cursor:null,evidence_pane:'list'});requestAnimationFrame(()=>focusBelowHeader(list.current?.querySelector<HTMLButtonElement>(`[data-artifact-id="${aid}"]`)??list.current));}}>Close artifact</button></section>}</div></>;
}
function ArtifactDetail({name,source:s,artifact:a,query,reference,onOpen}:{name:string;source:EvidenceSource;artifact:Artifact;query:SourceQuery;reference:string|null;onOpen:(element:HTMLElement|null)=>void}){
  const heading=useRef<HTMLHeadingElement>(null),open=useRef(onOpen);useEffect(()=>open.current(heading.current),[]);
  const supported=supportedMedia.includes(a.media_type)&&a.encoding==='UTF-8';
  return <><h3 ref={heading} tabIndex={-1}>{a.id} · revision {a.revision}</h3><p>{a.media_type} · {a.encoding} · {a.size_bytes??'Unknown'} bytes</p><details><summary>Supplied artifact coverage</summary><p>{a.coverage_complete ? "Coverage supplied as complete; this does not verify the artifact." : "Artifact coverage is incomplete."}</p>{a.omitted_ranges.length ? <ul>{a.omitted_ranges.map((r,i)=><li key={i}>Omitted bytes [{r.byte_start}, {r.byte_end}) · {r.explanation ?? "No omission explanation supplied."}</li>)}</ul> : <p>No omitted ranges supplied; this does not prove none exist.</p>}</details><p>Full artifact digest (supplied; not verified): <code>{a.full_digest??'Not supplied'}</code></p>{a.availability!=='AVAILABLE'?<p>{a.availability} — {a.explanation??'No artifact availability explanation supplied.'}</p>:!supported?<p>Unsupported media or encoding. No artifact body requested.</p>:<ExcerptView key={`${s.id}:${a.id}:${a.revision}`} name={name} source={s} artifact={a} query={query} reference={reference}/>}</>;
}
function ExcerptView({name,source:s,artifact:a,query:sourceQuery,reference}:{name:string;source:EvidenceSource;artifact:Artifact;query:SourceQuery;reference:string|null}){
  const {params}=useControls(),cursor=params.get('evidence_excerpt_cursor'),location=useLocation(),[message,setMessage]=useState('');
  const schema=useMemo(()=>evidenceSchemas.ExcerptResponse.superRefine(({data:v},ctx)=>{const issue=excerptIssue(v,s,a,cursor);if(issue)ctx.addIssue({code:'custom',message:issue});}),[s,a,cursor]);
  const route=`/sources/${s.id}/artifacts/${a.id}/excerpt?`+new URLSearchParams({case:name,artifact_revision:a.revision,...(cursor?{cursor}:{})}),query=useBoundedExcerpt(route,schema,sourceQuery.reader),x=query.data?.value.data;
  let formatted:string|null=null;if(x&&a.media_type==='application/json'&&x.complete_value){try{formatted=JSON.stringify(JSON.parse(x.text),null,2);}catch{/* Invalid or partial JSON stays source text. */}}
  return <>{query.error&&<ErrorState error={query.error} retry={()=>void query.refetch()}/>}{x?<><Note error={query.error}/><p>Bytes [{x.byte_start}, {x.byte_end}) · supplied lines {x.line_start??'Not supplied'}–{x.line_end??'Not supplied'}</p><p>{x.scope}</p>{x.truncated&&<p className="preview-note">Excerpt is truncated; ranges outside this excerpt are not displayed.</p>}<p>Excerpt SHA-256 verified: <code>{x.sha256}</code>. Full artifact integrity is not verified.</p>{a.media_type==='text/markdown'?<SafeContent format="markdown" text={visibleSource(x.text)}/>:<pre className="evidence-source"><code>{visibleSource(formatted??x.text)}</code></pre>}<p className="scope-note">Control and invisible formatting characters are shown as code-point markers. Digest and byte range identify original source, not rendered escaping. An excerpt does not establish complete coverage or causal benefit.</p><button onClick={()=>void navigator.clipboard.writeText(citation(s,a,x,dashboardCopyLink(location.pathname,location.search,window.location.origin),reference)).then(()=>setMessage('Pinned citation copied.')).catch(()=>setMessage('Clipboard unavailable; citation is available below.'))}>Copy citation</button><p role="status">{message}</p><details><summary>Pinned citation</summary><pre>{citation(s,a,x,dashboardCopyLink(location.pathname,location.search,window.location.origin),reference)}</pre></details><button onClick={()=>void query.refetch()}>Refresh excerpt</button><Pager next={x.next_cursor} cursorKey="evidence_excerpt_cursor" resetKey={`${name}:${s.id}:${a.id}:${a.revision}`}/></>:!query.error&&<p role="status">Loading bounded excerpt…</p>}</>;
}
